# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: forwarding-connectors).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.endpoints import Endpoints
from confident_ai.forwarding_connectors.types import (
    CreateForwardingConnectorRequest,
    ForwardingConnector,
    ForwardingConnectorHeaderConfig,
    ForwardingConnectorList,
    ForwardingConnectorRef,
    UpdateForwardingConnectorRequest,
)


class ForwardingConnectorsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> ForwardingConnectorList:
        """List Forwarding Connectors

        Lists the forwarding connectors in your Confident AI project one page at
        a time, newest first. Each connector is returned as a summary; retrieve
        one by id for its headers, environments and delivery history.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
            response_schema=ForwardingConnectorList,
            query={"page": page, "pageSize": page_size},
        )

    async def a_list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> ForwardingConnectorList:
        """List Forwarding Connectors

        Lists the forwarding connectors in your Confident AI project one page at
        a time, newest first. Each connector is returned as a summary; retrieve
        one by id for its headers, environments and delivery history.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
            response_schema=ForwardingConnectorList,
            query={"page": page, "pageSize": page_size},
        )

    def create(
        self,
        name: str,
        endpoint: str,
        *,
        headers: Optional[List[ForwardingConnectorHeaderConfig]] = None,
        environments: Optional[List[str]] = None,
        enabled: Optional[bool] = None
    ) -> ForwardingConnectorRef:
        """Create Forwarding Connector

        Creates a forwarding connector in your Confident AI project and returns
        its id. Confident AI then forwards traces from the environments you
        selected to your OTLP/HTTP collector, sending the headers you supplied
        with every batch. Header values are stored write-only: they are masked
        on every read, so keep your own copy.

        Args:
            name: The name of the connector, shown on the Confident AI platform
                and in forwarding failure messages.
            endpoint: The HTTPS URL of the OTLP/HTTP collector that receives the
                forwarded traces. It must resolve to a public address; private
                and loopback addresses are rejected.
            headers: The complete set of HTTP headers to send with every
                forwarded batch, alongside the `Content-Type:
                application/x-protobuf` header Confident AI sets. Omit this
                field to leave the stored headers untouched. When you do send
                it, the list replaces all stored headers, so resend every header
                you want to keep — including the ones whose values you read back
                masked, which are kept as stored.
            environments: The environments whose traces this connector forwards.
                An empty list forwards traces from every environment. Omit this
                field to leave the stored environments unchanged.
            enabled: Whether the connector forwards traces. Defaults to `true`
                on create; omit it on an update to leave it unchanged.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
            response_schema=ForwardingConnectorRef,
            request_schema=CreateForwardingConnectorRequest,
            body={
                "name": name,
                "endpoint": endpoint,
                "headers": headers,
                "environments": environments,
                "enabled": enabled,
            },
        )

    async def a_create(
        self,
        name: str,
        endpoint: str,
        *,
        headers: Optional[List[ForwardingConnectorHeaderConfig]] = None,
        environments: Optional[List[str]] = None,
        enabled: Optional[bool] = None
    ) -> ForwardingConnectorRef:
        """Create Forwarding Connector

        Creates a forwarding connector in your Confident AI project and returns
        its id. Confident AI then forwards traces from the environments you
        selected to your OTLP/HTTP collector, sending the headers you supplied
        with every batch. Header values are stored write-only: they are masked
        on every read, so keep your own copy.

        Args:
            name: The name of the connector, shown on the Confident AI platform
                and in forwarding failure messages.
            endpoint: The HTTPS URL of the OTLP/HTTP collector that receives the
                forwarded traces. It must resolve to a public address; private
                and loopback addresses are rejected.
            headers: The complete set of HTTP headers to send with every
                forwarded batch, alongside the `Content-Type:
                application/x-protobuf` header Confident AI sets. Omit this
                field to leave the stored headers untouched. When you do send
                it, the list replaces all stored headers, so resend every header
                you want to keep — including the ones whose values you read back
                masked, which are kept as stored.
            environments: The environments whose traces this connector forwards.
                An empty list forwards traces from every environment. Omit this
                field to leave the stored environments unchanged.
            enabled: Whether the connector forwards traces. Defaults to `true`
                on create; omit it on an update to leave it unchanged.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
            response_schema=ForwardingConnectorRef,
            request_schema=CreateForwardingConnectorRequest,
            body={
                "name": name,
                "endpoint": endpoint,
                "headers": headers,
                "environments": environments,
                "enabled": enabled,
            },
        )

    def get(self, forwarding_connector_id: str) -> ForwardingConnector:
        """Get Forwarding Connector

        Retrieves a forwarding connector by id, with its headers, the
        environments it forwards, and how its deliveries have gone. Header
        values come back masked, never in plaintext.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnector,
            path={"forwardingConnectorId": forwarding_connector_id},
        )

    async def a_get(self, forwarding_connector_id: str) -> ForwardingConnector:
        """Get Forwarding Connector

        Retrieves a forwarding connector by id, with its headers, the
        environments it forwards, and how its deliveries have gone. Header
        values come back masked, never in plaintext.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnector,
            path={"forwardingConnectorId": forwarding_connector_id},
        )

    def update(
        self,
        forwarding_connector_id: str,
        *,
        name: Optional[str] = None,
        endpoint: Optional[str] = None,
        headers: Optional[List[ForwardingConnectorHeaderConfig]] = None,
        environments: Optional[List[str]] = None,
        enabled: Optional[bool] = None
    ) -> ForwardingConnector:
        """Update Forwarding Connector

        Updates a forwarding connector and returns it. Every field you omit is
        left as stored.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
            name: The name of the connector.
            endpoint: The HTTPS URL of the OTLP/HTTP collector that receives the
                forwarded traces. It must resolve to a public address; private
                and loopback addresses are rejected.
            headers: The complete set of HTTP headers to send with every
                forwarded batch, alongside the `Content-Type:
                application/x-protobuf` header Confident AI sets. Omit this
                field to leave the stored headers untouched. When you do send
                it, the list replaces all stored headers, so resend every header
                you want to keep — including the ones whose values you read back
                masked, which are kept as stored.
            environments: The environments whose traces this connector forwards.
                An empty list forwards traces from every environment. Omit this
                field to leave the stored environments unchanged.
            enabled: Whether the connector forwards traces. Defaults to `true`
                on create; omit it on an update to leave it unchanged.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnector,
            request_schema=UpdateForwardingConnectorRequest,
            body={
                "name": name,
                "endpoint": endpoint,
                "headers": headers,
                "environments": environments,
                "enabled": enabled,
            },
            path={"forwardingConnectorId": forwarding_connector_id},
        )

    async def a_update(
        self,
        forwarding_connector_id: str,
        *,
        name: Optional[str] = None,
        endpoint: Optional[str] = None,
        headers: Optional[List[ForwardingConnectorHeaderConfig]] = None,
        environments: Optional[List[str]] = None,
        enabled: Optional[bool] = None
    ) -> ForwardingConnector:
        """Update Forwarding Connector

        Updates a forwarding connector and returns it. Every field you omit is
        left as stored.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
            name: The name of the connector.
            endpoint: The HTTPS URL of the OTLP/HTTP collector that receives the
                forwarded traces. It must resolve to a public address; private
                and loopback addresses are rejected.
            headers: The complete set of HTTP headers to send with every
                forwarded batch, alongside the `Content-Type:
                application/x-protobuf` header Confident AI sets. Omit this
                field to leave the stored headers untouched. When you do send
                it, the list replaces all stored headers, so resend every header
                you want to keep — including the ones whose values you read back
                masked, which are kept as stored.
            environments: The environments whose traces this connector forwards.
                An empty list forwards traces from every environment. Omit this
                field to leave the stored environments unchanged.
            enabled: Whether the connector forwards traces. Defaults to `true`
                on create; omit it on an update to leave it unchanged.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnector,
            request_schema=UpdateForwardingConnectorRequest,
            body={
                "name": name,
                "endpoint": endpoint,
                "headers": headers,
                "environments": environments,
                "enabled": enabled,
            },
            path={"forwardingConnectorId": forwarding_connector_id},
        )

    def delete(self, forwarding_connector_id: str) -> ForwardingConnectorRef:
        """Delete Forwarding Connector

        Permanently deletes a forwarding connector and the credentials stored in
        its headers. Traces already forwarded are unaffected.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnectorRef,
            path={"forwardingConnectorId": forwarding_connector_id},
        )

    async def a_delete(
        self, forwarding_connector_id: str
    ) -> ForwardingConnectorRef:
        """Delete Forwarding Connector

        Permanently deletes a forwarding connector and the credentials stored in
        its headers. Traces already forwarded are unaffected.

        Args:
            forwarding_connector_id: The id of the forwarding connector.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
            response_schema=ForwardingConnectorRef,
            path={"forwardingConnectorId": forwarding_connector_id},
        )
