# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: forwarding-connectors).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from pydantic import Field

from confident_ai.types import ConfidentBaseModel


class ForwardingConnectorHeaderConfig(ConfidentBaseModel):
    key: str
    value: str


class CreateForwardingConnectorRequest(ConfidentBaseModel):
    name: str
    endpoint: str
    headers: Optional[List[ForwardingConnectorHeaderConfig]] = None
    environments: Optional[List[str]] = None
    enabled: Optional[bool] = None


class ForwardingConnectorHeader(ConfidentBaseModel):
    key: str
    value: str


class ForwardingConnector(ConfidentBaseModel):
    id: str
    name: str
    endpoint: str
    headers: List[ForwardingConnectorHeader]
    environments: List[str]
    enabled: bool
    last_forwarded_at: Optional[str] = Field(alias="lastForwardedAt")
    last_error: Optional[str] = Field(alias="lastError")
    success_count: int = Field(alias="successCount")
    failure_count: int = Field(alias="failureCount")
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")


class ForwardingConnectorSummary(ConfidentBaseModel):
    id: str
    name: str
    endpoint: str
    enabled: bool


class ForwardingConnectorList(ConfidentBaseModel):
    forwarding_connectors: List[ForwardingConnectorSummary] = Field(
        alias="forwardingConnectors",
    )
    total_forwarding_connectors: int = Field(alias="totalForwardingConnectors")
    page: int
    page_size: int = Field(alias="pageSize")


class ForwardingConnectorRef(ConfidentBaseModel):
    id: str


class UpdateForwardingConnectorRequest(ConfidentBaseModel):
    name: Optional[str] = None
    endpoint: Optional[str] = None
    headers: Optional[List[ForwardingConnectorHeaderConfig]] = None
    environments: Optional[List[str]] = None
    enabled: Optional[bool] = None
