# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: spans).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Literal, Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.common.types import Span, SpanType
from confident_ai.endpoints import Endpoints
from confident_ai.spans.types import SpanList, SpanSortBy


class SpansClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[SpanSortBy] = None,
        environment: Optional[str] = None,
        type: Optional[SpanType] = None,
        trace_uuid: Optional[str] = None,
        name: Optional[str] = None,
        has_error: Optional[Literal["true", "false"]] = None,
        model: Optional[str] = None,
        prompt_alias: Optional[str] = None,
        prompt_version: Optional[str] = None,
        prompt_label: Optional[str] = None,
        prompt_commit_hash: Optional[str] = None,
        embedder: Optional[str] = None,
        top_k: Optional[int] = None,
        chunk_size: Optional[int] = None
    ) -> SpanList:
        """List Spans

        Lists the spans in your Confident AI project one page at a time, newest
        first by default, as summary rows. Retrieve a span by id for its full
        detail.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            environment: This filters the spans by the environment where their
                trace was created, and returns spans from all environments if
                not specified.
            type: Filter by the specific type of span.
            trace_uuid: Filter spans that belong to the trace with this uuid.
            name: Filter spans by their exact name.
            has_error: Filter for spans that either failed (`true`) or succeeded
                (`false`).
            model: Filter LLM spans by the model used.
            prompt_alias: This filters the spans by the prompt alias used.
            prompt_version: This filters the spans by the prompt version used.
            prompt_label: This filters the spans by the prompt label used.
            prompt_commit_hash: This filters the spans by the exact prompt
                commit hash used.
            embedder: Filter retriever spans by the embedder model used.
            top_k: Filter retriever spans by the `topK` value.
            chunk_size: Filter retriever spans by the chunk size.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.SPANS_ENDPOINT,
            response_schema=SpanList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
                "type": type,
                "traceUuid": trace_uuid,
                "name": name,
                "hasError": has_error,
                "model": model,
                "promptAlias": prompt_alias,
                "promptVersion": prompt_version,
                "promptLabel": prompt_label,
                "promptCommitHash": prompt_commit_hash,
                "embedder": embedder,
                "topK": top_k,
                "chunkSize": chunk_size,
            },
        )

    async def a_list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[SpanSortBy] = None,
        environment: Optional[str] = None,
        type: Optional[SpanType] = None,
        trace_uuid: Optional[str] = None,
        name: Optional[str] = None,
        has_error: Optional[Literal["true", "false"]] = None,
        model: Optional[str] = None,
        prompt_alias: Optional[str] = None,
        prompt_version: Optional[str] = None,
        prompt_label: Optional[str] = None,
        prompt_commit_hash: Optional[str] = None,
        embedder: Optional[str] = None,
        top_k: Optional[int] = None,
        chunk_size: Optional[int] = None
    ) -> SpanList:
        """List Spans

        Lists the spans in your Confident AI project one page at a time, newest
        first by default, as summary rows. Retrieve a span by id for its full
        detail.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            environment: This filters the spans by the environment where their
                trace was created, and returns spans from all environments if
                not specified.
            type: Filter by the specific type of span.
            trace_uuid: Filter spans that belong to the trace with this uuid.
            name: Filter spans by their exact name.
            has_error: Filter for spans that either failed (`true`) or succeeded
                (`false`).
            model: Filter LLM spans by the model used.
            prompt_alias: This filters the spans by the prompt alias used.
            prompt_version: This filters the spans by the prompt version used.
            prompt_label: This filters the spans by the prompt label used.
            prompt_commit_hash: This filters the spans by the exact prompt
                commit hash used.
            embedder: Filter retriever spans by the embedder model used.
            top_k: Filter retriever spans by the `topK` value.
            chunk_size: Filter retriever spans by the chunk size.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.SPANS_ENDPOINT,
            response_schema=SpanList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
                "type": type,
                "traceUuid": trace_uuid,
                "name": name,
                "hasError": has_error,
                "model": model,
                "promptAlias": prompt_alias,
                "promptVersion": prompt_version,
                "promptLabel": prompt_label,
                "promptCommitHash": prompt_commit_hash,
                "embedder": embedder,
                "topK": top_k,
                "chunkSize": chunk_size,
            },
        )

    def get(self, span_uuid: str) -> Span:
        """Get Span

        Retrieves a span by uuid from your Confident AI project, with its full
        input and output, evaluation fields, results and annotations.

        Args:
            span_uuid: The unique identifier of the span.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.SPAN_ENDPOINT,
            response_schema=Span,
            path={"spanUuid": span_uuid},
        )

    async def a_get(self, span_uuid: str) -> Span:
        """Get Span

        Retrieves a span by uuid from your Confident AI project, with its full
        input and output, evaluation fields, results and annotations.

        Args:
            span_uuid: The unique identifier of the span.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.SPAN_ENDPOINT,
            response_schema=Span,
            path={"spanUuid": span_uuid},
        )
