# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: traces).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Any, Dict, List, Literal, Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.common.types import ToolCall, Trace, TraceSpanStatus
from confident_ai.endpoints import Endpoints
from confident_ai.traces.types import (
    CreateTraceRequest,
    CustomerRequest,
    MetricDataConfig,
    SpanRequest,
    ThreadRequest,
    TraceAttachment,
    TraceList,
    TraceRef,
    TraceSortBy,
    UserRequest,
)


class TracesClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[TraceSortBy] = None,
        environment: Optional[str] = None,
        metadata: Optional[Dict[str, str]] = None
    ) -> TraceList:
        """List Traces

        Lists the traces in your Confident AI project one page at a time, newest
        first by default, as summary rows. Retrieve a trace by uuid for its full
        detail.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            environment: This filters the traces by the environment where the
                trace was created, and returns traces from all environments if
                not specified.
            metadata: Filter traces by metadata key-value pairs using bracket
                notation, for example `metadata[client]=acme-corp`. Every pair
                must match.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.TRACES_ENDPOINT,
            response_schema=TraceList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
                "metadata": metadata,
            },
        )

    async def a_list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[TraceSortBy] = None,
        environment: Optional[str] = None,
        metadata: Optional[Dict[str, str]] = None
    ) -> TraceList:
        """List Traces

        Lists the traces in your Confident AI project one page at a time, newest
        first by default, as summary rows. Retrieve a trace by uuid for its full
        detail.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            environment: This filters the traces by the environment where the
                trace was created, and returns traces from all environments if
                not specified.
            metadata: Filter traces by metadata key-value pairs using bracket
                notation, for example `metadata[client]=acme-corp`. Every pair
                must match.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.TRACES_ENDPOINT,
            response_schema=TraceList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
                "metadata": metadata,
            },
        )

    def create(
        self,
        uuid: str,
        start_time: str,
        end_time: str,
        *,
        name: Optional[str] = None,
        input: Optional[Any] = None,
        output: Optional[Any] = None,
        status: Optional[TraceSpanStatus] = None,
        environment: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        thread_id: Optional[str] = None,
        thread: Optional[ThreadRequest] = None,
        user_id: Optional[str] = None,
        user: Optional[UserRequest] = None,
        customer_id: Optional[str] = None,
        customer: Optional[CustomerRequest] = None,
        metric_collection: Optional[str] = None,
        test_run_id: Optional[str] = None,
        test_case_id: Optional[str] = None,
        turn_id: Optional[str] = None,
        retrieval_context: Optional[List[str]] = None,
        context: Optional[List[str]] = None,
        expected_output: Optional[str] = None,
        tools_called: Optional[List[ToolCall]] = None,
        expected_tools: Optional[List[ToolCall]] = None,
        spans: Optional[List[SpanRequest]] = None,
        metrics_data: Optional[List[MetricDataConfig]] = None,
        attachments: Optional[Dict[str, TraceAttachment]] = None
    ) -> TraceRef:
        """Create Trace

        Creates a trace in your Confident AI project, along with the spans it
        contains, and returns its uuid. A `uuid` that is not a UUID is hashed
        into one, so the returned value is what every later lookup uses.

        Args:
            uuid: The unique identifier of the trace, generated by your
                application. Values that are not UUIDs are hashed into one, and
                the hashed uuid is what the response and every later lookup use.
            start_time: This is the time the trace started, as an ISO 8601
                datetime.
            end_time: This is the time the trace ended, as an ISO 8601 datetime.
            name: This is the name of the trace.
            input: This is the input to the trace, as a string or any JSON
                value.
            output: This is the output of the trace, as a string or any JSON
                value.
            environment: This is the environment where your trace was posted,
                which helps with separating and debugging traces from different
                environments on the Confident AI platform. Any name up to 64
                characters is accepted, for example production, staging or eu-
                prod.
            metadata: This is any additional metadata associated with the trace.
            tags: This is any tags associated with the trace, which helps with
                grouping traces and filtering them on the Confident AI platform.
            thread_id: This is the unique identifier of the thread associated
                with the trace, which groups traces in the same thread into a
                conversation.
            user_id: This is the unique identifier for your end user for the
                trace.
            customer_id: This is the unique identifier of the customer the trace
                belongs to — the account, tenant or organization your end user
                belongs to.
            metric_collection: This is the metric collection you wish to use to
                evaluate the trace.
            test_run_id: This is the unique identifier of the test run to
                associate the trace with. When set, the trace becomes one test
                case in that test run and `metricCollection` is required. It
                cannot be combined with `testCaseId`.
            test_case_id: The id of an existing test case to attach the trace
                to, when the trace was produced while evaluating that test case.
            turn_id: The id of the conversational test case turn to attach the
                trace to, when the trace was produced while evaluating that
                turn.
            retrieval_context: This is the retrieval context of your trace,
                which is to be used for evaluation.
            context: This is the ideal retrieval context of your trace, which is
                to be used for evaluation.
            expected_output: This is the expected output of your trace, which is
                the ideal actual output and to be used for evaluation.
            tools_called: This is the tools called by your trace, which is to be
                used for evaluation.
            expected_tools: This is the expected tools to be called by the
                trace, which is to be used for evaluation.
            spans: This is the list of spans in the trace. Each span's `type`
                decides which fields it accepts.
            metrics_data: Metric results you already computed for this trace,
                recorded as-is instead of being evaluated by Confident AI.
            attachments: Map of attachment ids to payloads for all
                `[DEEPEVAL:IMAGE:…]` and `[DEEPEVAL:PDF:…]` markers in this
                trace. Define attachments at the trace level with the same ids
                for the same instances.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.TRACES_ENDPOINT,
            response_schema=TraceRef,
            request_schema=CreateTraceRequest,
            body={
                "uuid": uuid,
                "startTime": start_time,
                "endTime": end_time,
                "name": name,
                "input": input,
                "output": output,
                "status": status,
                "environment": environment,
                "metadata": metadata,
                "tags": tags,
                "threadId": thread_id,
                "thread": thread,
                "userId": user_id,
                "user": user,
                "customerId": customer_id,
                "customer": customer,
                "metricCollection": metric_collection,
                "testRunId": test_run_id,
                "testCaseId": test_case_id,
                "turnId": turn_id,
                "retrievalContext": retrieval_context,
                "context": context,
                "expectedOutput": expected_output,
                "toolsCalled": tools_called,
                "expectedTools": expected_tools,
                "spans": spans,
                "metricsData": metrics_data,
                "attachments": attachments,
            },
        )

    async def a_create(
        self,
        uuid: str,
        start_time: str,
        end_time: str,
        *,
        name: Optional[str] = None,
        input: Optional[Any] = None,
        output: Optional[Any] = None,
        status: Optional[TraceSpanStatus] = None,
        environment: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        thread_id: Optional[str] = None,
        thread: Optional[ThreadRequest] = None,
        user_id: Optional[str] = None,
        user: Optional[UserRequest] = None,
        customer_id: Optional[str] = None,
        customer: Optional[CustomerRequest] = None,
        metric_collection: Optional[str] = None,
        test_run_id: Optional[str] = None,
        test_case_id: Optional[str] = None,
        turn_id: Optional[str] = None,
        retrieval_context: Optional[List[str]] = None,
        context: Optional[List[str]] = None,
        expected_output: Optional[str] = None,
        tools_called: Optional[List[ToolCall]] = None,
        expected_tools: Optional[List[ToolCall]] = None,
        spans: Optional[List[SpanRequest]] = None,
        metrics_data: Optional[List[MetricDataConfig]] = None,
        attachments: Optional[Dict[str, TraceAttachment]] = None
    ) -> TraceRef:
        """Create Trace

        Creates a trace in your Confident AI project, along with the spans it
        contains, and returns its uuid. A `uuid` that is not a UUID is hashed
        into one, so the returned value is what every later lookup uses.

        Args:
            uuid: The unique identifier of the trace, generated by your
                application. Values that are not UUIDs are hashed into one, and
                the hashed uuid is what the response and every later lookup use.
            start_time: This is the time the trace started, as an ISO 8601
                datetime.
            end_time: This is the time the trace ended, as an ISO 8601 datetime.
            name: This is the name of the trace.
            input: This is the input to the trace, as a string or any JSON
                value.
            output: This is the output of the trace, as a string or any JSON
                value.
            environment: This is the environment where your trace was posted,
                which helps with separating and debugging traces from different
                environments on the Confident AI platform. Any name up to 64
                characters is accepted, for example production, staging or eu-
                prod.
            metadata: This is any additional metadata associated with the trace.
            tags: This is any tags associated with the trace, which helps with
                grouping traces and filtering them on the Confident AI platform.
            thread_id: This is the unique identifier of the thread associated
                with the trace, which groups traces in the same thread into a
                conversation.
            user_id: This is the unique identifier for your end user for the
                trace.
            customer_id: This is the unique identifier of the customer the trace
                belongs to — the account, tenant or organization your end user
                belongs to.
            metric_collection: This is the metric collection you wish to use to
                evaluate the trace.
            test_run_id: This is the unique identifier of the test run to
                associate the trace with. When set, the trace becomes one test
                case in that test run and `metricCollection` is required. It
                cannot be combined with `testCaseId`.
            test_case_id: The id of an existing test case to attach the trace
                to, when the trace was produced while evaluating that test case.
            turn_id: The id of the conversational test case turn to attach the
                trace to, when the trace was produced while evaluating that
                turn.
            retrieval_context: This is the retrieval context of your trace,
                which is to be used for evaluation.
            context: This is the ideal retrieval context of your trace, which is
                to be used for evaluation.
            expected_output: This is the expected output of your trace, which is
                the ideal actual output and to be used for evaluation.
            tools_called: This is the tools called by your trace, which is to be
                used for evaluation.
            expected_tools: This is the expected tools to be called by the
                trace, which is to be used for evaluation.
            spans: This is the list of spans in the trace. Each span's `type`
                decides which fields it accepts.
            metrics_data: Metric results you already computed for this trace,
                recorded as-is instead of being evaluated by Confident AI.
            attachments: Map of attachment ids to payloads for all
                `[DEEPEVAL:IMAGE:…]` and `[DEEPEVAL:PDF:…]` markers in this
                trace. Define attachments at the trace level with the same ids
                for the same instances.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.TRACES_ENDPOINT,
            response_schema=TraceRef,
            request_schema=CreateTraceRequest,
            body={
                "uuid": uuid,
                "startTime": start_time,
                "endTime": end_time,
                "name": name,
                "input": input,
                "output": output,
                "status": status,
                "environment": environment,
                "metadata": metadata,
                "tags": tags,
                "threadId": thread_id,
                "thread": thread,
                "userId": user_id,
                "user": user,
                "customerId": customer_id,
                "customer": customer,
                "metricCollection": metric_collection,
                "testRunId": test_run_id,
                "testCaseId": test_case_id,
                "turnId": turn_id,
                "retrievalContext": retrieval_context,
                "context": context,
                "expectedOutput": expected_output,
                "toolsCalled": tools_called,
                "expectedTools": expected_tools,
                "spans": spans,
                "metricsData": metrics_data,
                "attachments": attachments,
            },
        )

    def get(self, trace_uuid: str) -> Trace:
        """Get Trace

        Retrieves a trace by uuid from your Confident AI project, with its
        spans, full input and output, evaluation fields, classifier labels,
        results and annotations.

        Args:
            trace_uuid: The unique identifier of the trace.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.TRACE_ENDPOINT,
            response_schema=Trace,
            path={"traceUuid": trace_uuid},
        )

    async def a_get(self, trace_uuid: str) -> Trace:
        """Get Trace

        Retrieves a trace by uuid from your Confident AI project, with its
        spans, full input and output, evaluation fields, classifier labels,
        results and annotations.

        Args:
            trace_uuid: The unique identifier of the trace.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.TRACE_ENDPOINT,
            response_schema=Trace,
            path={"traceUuid": trace_uuid},
        )
