# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: traces).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import Field

from confident_ai.common.types import (
    EvaluationErrorType,
    ToolCall,
    TraceSpanStatus,
)
from confident_ai.types import ConfidentBaseModel


class TraceSortBy(Enum):
    CREATEDAT = "createdAt"
    ENDEDAT = "endedAt"


class MetricDataConfig(ConfidentBaseModel):
    name: str
    score: Optional[float] = None
    success: Optional[bool] = None
    threshold: Optional[float] = None
    strict_mode: Optional[bool] = Field(default=None, alias="strictMode")
    flaky: Optional[bool] = None
    reason: Optional[str] = None
    evaluation_model: Optional[str] = Field(
        default=None,
        alias="evaluationModel",
    )
    evaluation_cost: Optional[float] = Field(
        default=None,
        alias="evaluationCost",
    )
    error: Optional[str] = None
    error_type: Optional[EvaluationErrorType] = Field(
        default=None,
        alias="errorType",
    )
    verbose_logs: Optional[str] = Field(default=None, alias="verboseLogs")


class AgentSpanRequest(ConfidentBaseModel):
    type: Literal["AGENT"]
    uuid: str
    name: str
    input: Optional[Any] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    status: Optional[TraceSpanStatus] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    parent_uuid: Optional[str] = Field(default=None, alias="parentUuid")
    metadata: Optional[Dict[str, Any]] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    integration: Optional[str] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )
    available_tools: List[str] = Field(alias="availableTools")
    agent_handoffs: List[str] = Field(alias="agentHandoffs")


class BaseSpanRequest(ConfidentBaseModel):
    type: Optional[Literal["SPAN"]] = None
    uuid: str
    name: str
    input: Optional[Any] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    status: Optional[TraceSpanStatus] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    parent_uuid: Optional[str] = Field(default=None, alias="parentUuid")
    metadata: Optional[Dict[str, Any]] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    integration: Optional[str] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )


class ThreadRequest(ConfidentBaseModel):
    id: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None


class UserRequest(ConfidentBaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class CustomerRequest(ConfidentBaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class LlmSpanRequest(ConfidentBaseModel):
    type: Literal["LLM"]
    uuid: str
    name: str
    input: Optional[Any] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    status: Optional[TraceSpanStatus] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    parent_uuid: Optional[str] = Field(default=None, alias="parentUuid")
    metadata: Optional[Dict[str, Any]] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    integration: Optional[str] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )
    model: Optional[str] = None
    provider: Optional[str] = None
    endpoint: Optional[str] = None
    cost_per_input_token: Optional[float] = Field(
        default=None,
        alias="costPerInputToken",
    )
    cost_per_output_token: Optional[float] = Field(
        default=None,
        alias="costPerOutputToken",
    )
    input_token_count: Optional[int] = Field(
        default=None,
        alias="inputTokenCount",
    )
    output_token_count: Optional[int] = Field(
        default=None,
        alias="outputTokenCount",
    )
    prompt_alias: Optional[str] = Field(default=None, alias="promptAlias")
    prompt_version: Optional[str] = Field(default=None, alias="promptVersion")
    prompt_label: Optional[str] = Field(default=None, alias="promptLabel")
    prompt_commit_hash: Optional[str] = Field(
        default=None,
        alias="promptCommitHash",
    )


class RetrieverSpanRequest(ConfidentBaseModel):
    type: Literal["RETRIEVER"]
    uuid: str
    name: str
    input: Optional[Any] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    status: Optional[TraceSpanStatus] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    parent_uuid: Optional[str] = Field(default=None, alias="parentUuid")
    metadata: Optional[Dict[str, Any]] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    integration: Optional[str] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )
    embedder: str
    top_k: Optional[int] = Field(default=None, alias="topK")
    chunk_size: Optional[int] = Field(default=None, alias="chunkSize")


class ToolSpanRequest(ConfidentBaseModel):
    type: Literal["TOOL"]
    uuid: str
    name: str
    input: Optional[Any] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    status: Optional[TraceSpanStatus] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    parent_uuid: Optional[str] = Field(default=None, alias="parentUuid")
    metadata: Optional[Dict[str, Any]] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    integration: Optional[str] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )
    description: Optional[str] = None


SpanRequest = Union[
    BaseSpanRequest,
    LlmSpanRequest,
    RetrieverSpanRequest,
    ToolSpanRequest,
    AgentSpanRequest,
]


class TraceAttachment(ConfidentBaseModel):
    url: Optional[str] = None
    data_base64: Optional[str] = Field(default=None, alias="dataBase64")
    mime_type: Optional[str] = Field(default=None, alias="mimeType")


class CreateTraceRequest(ConfidentBaseModel):
    uuid: str
    name: Optional[str] = None
    input: Optional[Any] = None
    output: Optional[Any] = None
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    status: Optional[TraceSpanStatus] = None
    environment: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    thread_id: Optional[str] = Field(default=None, alias="threadId")
    thread: Optional[ThreadRequest] = None
    user_id: Optional[str] = Field(default=None, alias="userId")
    user: Optional[UserRequest] = None
    customer_id: Optional[str] = Field(default=None, alias="customerId")
    customer: Optional[CustomerRequest] = None
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    test_run_id: Optional[str] = Field(default=None, alias="testRunId")
    test_case_id: Optional[str] = Field(default=None, alias="testCaseId")
    turn_id: Optional[str] = Field(default=None, alias="turnId")
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    context: Optional[List[str]] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    spans: Optional[List[SpanRequest]] = None
    metrics_data: Optional[List[MetricDataConfig]] = Field(
        default=None,
        alias="metricsData",
    )
    attachments: Optional[Dict[str, TraceAttachment]] = None


class TraceSummary(ConfidentBaseModel):
    uuid: str
    name: Optional[str]
    status: TraceSpanStatus
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    latency: int
    cost: Optional[float]
    thread_id: Optional[str] = Field(alias="threadId")
    user_id: Optional[str] = Field(alias="userId")
    customer_id: Optional[str] = Field(alias="customerId")
    environment: str
    tags: Optional[List[str]]
    metadata: Optional[Dict[str, Any]]
    input_preview: Optional[str] = Field(alias="inputPreview")
    output_preview: Optional[str] = Field(alias="outputPreview")


class TraceList(ConfidentBaseModel):
    traces: List[TraceSummary]
    total_traces: Optional[int] = Field(default=None, alias="totalTraces")
    next_cursor: Optional[str] = Field(alias="nextCursor")


class TraceRef(ConfidentBaseModel):
    uuid: str
