// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: scheduled-alerts).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  FilterSet,
  ScheduleIntervalUnit,
  ScheduleRecurrenceType,
} from "../common/types";

export enum AlertDataModel {
  TRACE = "TRACE",
  SPAN = "SPAN",
  LLM_SPAN = "LLM_SPAN",
  AGENT_SPAN = "AGENT_SPAN",
  RETRIEVER_SPAN = "RETRIEVER_SPAN",
  TOOL_SPAN = "TOOL_SPAN",
  CUSTOM_SPAN = "CUSTOM_SPAN",
  THREAD = "THREAD",
}

export enum AlertSeverity {
  CRITICAL = "CRITICAL",
  ERROR = "ERROR",
  WARNING = "WARNING",
  INFO = "INFO",
}

export enum AlertThresholdDirection {
  ABOVE = "above",
  BELOW = "below",
}

export enum ScheduledAlertType {
  THRESHOLD = "THRESHOLD",
  REGRESSION = "REGRESSION",
  ANOMALY = "ANOMALY",
  SIGNAL_SPIKE = "SIGNAL_SPIKE",
}

export interface AlertThresholdSettings {
  value: number;
  direction: AlertThresholdDirection;
}

export interface AnomalyDetectionSettings {
  traceName?: string;
  metrics?: (
    | "avg_score"
    | "error_rate"
    | "avg_latency"
    | "avg_cost"
    | "negative_label_rate"
  )[];
  direction: "WORSENED" | "ANY";
  minAffectedCount: number;
}

export interface RegressionDetectionSettings {
  traceName?: string;
  metrics?: (
    | "avg_score"
    | "error_rate"
    | "avg_latency"
    | "avg_cost"
    | "negative_label_rate"
  )[];
  direction: "WORSENED" | "ANY";
  minAffectedCount: number;
  significantOnly: boolean;
}

export interface SignalSpikeDetectionSettings {
  classifierIds: string[];
  direction: "WORSENED" | "ANY";
  minAffectedCount: number;
}

export type ScheduledAlertDetectionSettings =
  | RegressionDetectionSettings
  | AnomalyDetectionSettings
  | SignalSpikeDetectionSettings;

export interface CreateScheduledAlertRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  description?: string | null;
  filters?: FilterSet | null;
  severity?: AlertSeverity;
  name: string;
  type?: ScheduledAlertType;
  dataModel: AlertDataModel;
  aggregation?: string;
  thresholdSettings?: AlertThresholdSettings;
  detectionSettings?: ScheduledAlertDetectionSettings;
  enabled?: boolean;
}

export interface ScheduledAlertScheduleSettings {
  recurrence: ScheduleRecurrenceType;
  repeatEvery: number | null;
  repeatUnit: ScheduleIntervalUnit | null;
  startAt: string | null;
  endAt: string | null;
  maxRuns: number | null;
  runCount: number;
  lastRunAt: string | null;
  enabled: boolean;
}

export interface ScheduledAlert {
  id: string;
  name: string;
  description: string | null;
  type: ScheduledAlertType;
  dataModel: AlertDataModel;
  aggregation: string | null;
  filters: FilterSet;
  thresholdSettings: AlertThresholdSettings | null;
  detectionSettings:
    | RegressionDetectionSettings
    | AnomalyDetectionSettings
    | SignalSpikeDetectionSettings
    | null;
  severity: AlertSeverity;
  scheduleSettings: ScheduledAlertScheduleSettings | null;
}

export interface ScheduledAlertSummary {
  id: string;
  name: string;
  type: ScheduledAlertType;
  dataModel: AlertDataModel;
  enabled: boolean;
}

export interface ScheduledAlertList {
  scheduledAlerts: ScheduledAlertSummary[];
  totalScheduledAlerts: number;
  page: number;
  pageSize: number;
}

export interface ScheduledAlertRef {
  id: string;
}

export interface UpdateScheduledAlertRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  description?: string | null;
  filters?: FilterSet | null;
  severity?: AlertSeverity;
  name?: string;
  type?: ScheduledAlertType;
  dataModel?: AlertDataModel;
  aggregation?: string;
  thresholdSettings?: AlertThresholdSettings;
  detectionSettings?: ScheduledAlertDetectionSettings;
  enabled?: boolean;
}
