# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: test-runs).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import Field

from confident_ai.common.types import EvaluationErrorType, ToolCall, Turn
from confident_ai.types import ConfidentBaseModel


class TestCaseResultStatus(Enum):
    ACCEPTED = "accepted"
    ALREADY_RECEIVED = "already_received"


class TestRunStatus(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ERRORED = "ERRORED"
    CANCELLED = "CANCELLED"


class SummaryOverview(ConfidentBaseModel):
    summary: List[str]
    action_items: List[str] = Field(alias="actionItems")


class SummaryPoint(ConfidentBaseModel):
    content: str
    test_case_ids: List[str] = Field(alias="testCaseIds")
    grade: Optional[float] = None


class TopicSummary(ConfidentBaseModel):
    topic: str
    summary_points: List[SummaryPoint] = Field(alias="summaryPoints")
    test_case_ids: List[str] = Field(alias="testCaseIds")


class AiInsightsSummary(ConfidentBaseModel):
    summary_overview: SummaryOverview = Field(alias="summaryOverview")
    topic_summaries: List[TopicSummary] = Field(alias="topicSummaries")


class CreateTestRunRequest(ConfidentBaseModel):
    metric_collection: Optional[str] = Field(
        default=None,
        alias="metricCollection",
    )
    identifier: Optional[str] = None


class MetricScores(ConfidentBaseModel):
    metric: str
    scores: List[float]
    passes: int
    fails: int
    errors: int
    error_type: Optional[EvaluationErrorType] = Field(alias="errorType")


class SubmitTestCaseResultRequest(ConfidentBaseModel):
    actual_output: Optional[str] = Field(default=None, alias="actualOutput")
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    token_cost: Optional[float] = Field(default=None, alias="tokenCost")
    input_token_count: Optional[int] = Field(
        default=None,
        alias="inputTokenCount",
    )
    output_token_count: Optional[int] = Field(
        default=None,
        alias="outputTokenCount",
    )
    metadata: Optional[Dict[str, Any]] = None


class SubmittedTestCaseResult(ConfidentBaseModel):
    test_case_id: str = Field(alias="testCaseId")
    status: TestCaseResultStatus


class TestCaseMetricData(ConfidentBaseModel):
    id: str
    name: str
    score: Optional[float]
    reason: Optional[str]
    success: Optional[bool]
    threshold: Optional[float]
    strict_mode: bool = Field(alias="strictMode")
    skipped: bool
    flaky: bool
    evaluation_model: Optional[str] = Field(alias="evaluationModel")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    error: Optional[str]
    error_type: Optional[EvaluationErrorType] = Field(alias="errorType")
    created_at: str = Field(alias="createdAt")
    evaluated_at: Optional[str] = Field(alias="evaluatedAt")
    trace_uuid: Optional[str] = Field(alias="traceUuid")
    span_uuid: Optional[str] = Field(alias="spanUuid")


class TestCaseTrace(ConfidentBaseModel):
    uuid: str
    name: Optional[str]
    input: Optional[str]
    output: Optional[str]
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    environment: str
    metadata: Optional[Dict[str, Any]]
    tags: Optional[List[str]]
    thread_id: Optional[str] = Field(alias="threadId")
    user_id: Optional[str] = Field(alias="userId")
    metric_collection_name: Optional[str] = Field(alias="metricCollectionName")
    retrieval_context: Optional[List[str]] = Field(alias="retrievalContext")
    context: Optional[List[str]]
    expected_output: Optional[str] = Field(alias="expectedOutput")
    tools_called: Optional[List[ToolCall]] = Field(alias="toolsCalled")
    expected_tools: Optional[List[ToolCall]] = Field(alias="expectedTools")


class TestRunSingleTurnTestCase(ConfidentBaseModel):
    input: Optional[str]
    actual_output: Optional[str] = Field(alias="actualOutput")
    expected_output: Optional[str] = Field(alias="expectedOutput")
    context: Optional[List[str]]
    retrieval_context: Optional[List[str]] = Field(alias="retrievalContext")
    tools_called: Optional[List[ToolCall]] = Field(alias="toolsCalled")
    expected_tools: Optional[List[ToolCall]] = Field(alias="expectedTools")
    id: str
    name: str
    success: Optional[bool]
    run_duration: Optional[float] = Field(alias="runDuration")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    comments: Optional[str]
    additional_metadata: Optional[Dict[str, Any]] = Field(
        alias="additionalMetadata",
    )
    metrics_data: List[TestCaseMetricData] = Field(alias="metricsData")


class TestRunMultiTurnTestCase(ConfidentBaseModel):
    turns: List[Turn]
    scenario: Optional[str]
    expected_outcome: Optional[str] = Field(alias="expectedOutcome")
    user_description: Optional[str] = Field(alias="userDescription")
    context: Optional[List[str]]
    id: str
    name: str
    success: Optional[bool]
    run_duration: Optional[float] = Field(alias="runDuration")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    comments: Optional[str]
    additional_metadata: Optional[Dict[str, Any]] = Field(
        alias="additionalMetadata",
    )
    metrics_data: List[TestCaseMetricData] = Field(alias="metricsData")


class TestRunTraceTestCase(ConfidentBaseModel):
    trace: TestCaseTrace
    id: str
    name: str
    success: Optional[bool]
    run_duration: Optional[float] = Field(alias="runDuration")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    comments: Optional[str]
    additional_metadata: Optional[Dict[str, Any]] = Field(
        alias="additionalMetadata",
    )
    metrics_data: List[TestCaseMetricData] = Field(alias="metricsData")


TestRunTestCase = Union[
    TestRunSingleTurnTestCase, TestRunMultiTurnTestCase, TestRunTraceTestCase
]


class TestRun(ConfidentBaseModel):
    id: str
    created_at: str = Field(alias="createdAt")
    identifier: Optional[str]
    status: TestRunStatus
    multi_turn: bool = Field(alias="multiTurn")
    tests_passed: int = Field(alias="testsPassed")
    tests_failed: int = Field(alias="testsFailed")
    total_tests: int = Field(alias="totalTests")
    metrics_scores: List[MetricScores] = Field(alias="metricsScores")
    run_duration: float = Field(alias="runDuration")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    dataset_alias: Optional[str] = Field(alias="datasetAlias")
    test_file: Optional[str] = Field(alias="testFile")
    summary: Optional[AiInsightsSummary]
    test_cases: List[TestRunTestCase] = Field(alias="testCases")


class TestRunSummary(ConfidentBaseModel):
    id: str
    created_at: str = Field(alias="createdAt")
    identifier: Optional[str]
    status: TestRunStatus
    multi_turn: bool = Field(alias="multiTurn")
    tests_passed: int = Field(alias="testsPassed")
    tests_failed: int = Field(alias="testsFailed")
    total_tests: int = Field(alias="totalTests")
    metrics_scores: List[MetricScores] = Field(alias="metricsScores")
    run_duration: float = Field(alias="runDuration")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    dataset_alias: Optional[str] = Field(alias="datasetAlias")
    test_file: Optional[str] = Field(alias="testFile")
    summary: Optional[AiInsightsSummary]


class TestRunList(ConfidentBaseModel):
    test_runs: List[TestRunSummary] = Field(alias="testRuns")
    total_test_runs: int = Field(alias="totalTestRuns")
    page: int
    page_size: int = Field(alias="pageSize")


class TestRunRef(ConfidentBaseModel):
    id: str
