# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: scheduled-alerts).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import Field

from confident_ai.common.types import (
    FilterSet,
    ScheduleIntervalUnit,
    ScheduleRecurrenceType,
)
from confident_ai.types import ConfidentBaseModel


class AlertDataModel(Enum):
    TRACE = "TRACE"
    SPAN = "SPAN"
    LLM_SPAN = "LLM_SPAN"
    AGENT_SPAN = "AGENT_SPAN"
    RETRIEVER_SPAN = "RETRIEVER_SPAN"
    TOOL_SPAN = "TOOL_SPAN"
    CUSTOM_SPAN = "CUSTOM_SPAN"
    THREAD = "THREAD"


class AlertSeverity(Enum):
    CRITICAL = "CRITICAL"
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


class AlertThresholdDirection(Enum):
    ABOVE = "above"
    BELOW = "below"


class ScheduledAlertType(Enum):
    THRESHOLD = "THRESHOLD"
    REGRESSION = "REGRESSION"
    ANOMALY = "ANOMALY"
    SIGNAL_SPIKE = "SIGNAL_SPIKE"


class AlertThresholdSettings(ConfidentBaseModel):
    value: float
    direction: AlertThresholdDirection


class AnomalyDetectionSettings(ConfidentBaseModel):
    trace_name: Optional[str] = Field(default=None, alias="traceName")
    metrics: Optional[
        List[
            Literal[
                "avg_score",
                "error_rate",
                "avg_latency",
                "avg_cost",
                "negative_label_rate",
            ]
        ]
    ] = None
    direction: Literal["WORSENED", "ANY"]
    min_affected_count: int = Field(alias="minAffectedCount")


class RegressionDetectionSettings(ConfidentBaseModel):
    trace_name: Optional[str] = Field(default=None, alias="traceName")
    metrics: Optional[
        List[
            Literal[
                "avg_score",
                "error_rate",
                "avg_latency",
                "avg_cost",
                "negative_label_rate",
            ]
        ]
    ] = None
    direction: Literal["WORSENED", "ANY"]
    min_affected_count: int = Field(alias="minAffectedCount")
    significant_only: bool = Field(alias="significantOnly")


class SignalSpikeDetectionSettings(ConfidentBaseModel):
    classifier_ids: List[str] = Field(alias="classifierIds")
    direction: Literal["WORSENED", "ANY"]
    min_affected_count: int = Field(alias="minAffectedCount")


ScheduledAlertDetectionSettings = Union[
    RegressionDetectionSettings,
    AnomalyDetectionSettings,
    SignalSpikeDetectionSettings,
]


class CreateScheduledAlertRequest(ConfidentBaseModel):
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")
    description: Optional[str] = None
    filters: Optional[FilterSet] = None
    severity: Optional[AlertSeverity] = None
    name: str
    type: Optional[ScheduledAlertType] = None
    data_model: AlertDataModel = Field(alias="dataModel")
    aggregation: Optional[str] = None
    threshold_settings: Optional[AlertThresholdSettings] = Field(
        default=None,
        alias="thresholdSettings",
    )
    detection_settings: Optional[ScheduledAlertDetectionSettings] = Field(
        default=None,
        alias="detectionSettings",
    )
    enabled: Optional[bool] = None


class ScheduledAlertScheduleSettings(ConfidentBaseModel):
    recurrence: ScheduleRecurrenceType
    repeat_every: Optional[int] = Field(alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(alias="repeatUnit")
    start_at: Optional[str] = Field(alias="startAt")
    end_at: Optional[str] = Field(alias="endAt")
    max_runs: Optional[int] = Field(alias="maxRuns")
    run_count: int = Field(alias="runCount")
    last_run_at: Optional[str] = Field(alias="lastRunAt")
    enabled: bool


class ScheduledAlert(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]
    type: ScheduledAlertType
    data_model: AlertDataModel = Field(alias="dataModel")
    aggregation: Optional[str]
    filters: FilterSet
    threshold_settings: Optional[AlertThresholdSettings] = Field(
        alias="thresholdSettings",
    )
    detection_settings: Optional[
        Union[
            RegressionDetectionSettings,
            AnomalyDetectionSettings,
            SignalSpikeDetectionSettings,
        ]
    ] = Field(
        alias="detectionSettings",
    )
    severity: AlertSeverity
    schedule_settings: Optional[ScheduledAlertScheduleSettings] = Field(
        alias="scheduleSettings",
    )


class ScheduledAlertSummary(ConfidentBaseModel):
    id: str
    name: str
    type: ScheduledAlertType
    data_model: AlertDataModel = Field(alias="dataModel")
    enabled: bool


class ScheduledAlertList(ConfidentBaseModel):
    scheduled_alerts: List[ScheduledAlertSummary] = Field(
        alias="scheduledAlerts",
    )
    total_scheduled_alerts: int = Field(alias="totalScheduledAlerts")
    page: int
    page_size: int = Field(alias="pageSize")


class ScheduledAlertRef(ConfidentBaseModel):
    id: str


class UpdateScheduledAlertRequest(ConfidentBaseModel):
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")
    description: Optional[str] = None
    filters: Optional[FilterSet] = None
    severity: Optional[AlertSeverity] = None
    name: Optional[str] = None
    type: Optional[ScheduledAlertType] = None
    data_model: Optional[AlertDataModel] = Field(
        default=None,
        alias="dataModel",
    )
    aggregation: Optional[str] = None
    threshold_settings: Optional[AlertThresholdSettings] = Field(
        default=None,
        alias="thresholdSettings",
    )
    detection_settings: Optional[ScheduledAlertDetectionSettings] = Field(
        default=None,
        alias="detectionSettings",
    )
    enabled: Optional[bool] = None
