// @generated by scripts/generate_sdk.py from
// the shapes shared across packages/shared/openapi/openapi.yml.
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

export enum AnnotationFieldType {
  TEXT = "TEXT",
  NUMBER = "NUMBER",
  FLOAT = "FLOAT",
  BOOLEAN = "BOOLEAN",
  CHOICE = "CHOICE",
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  FIVE_STAR_RATING = "FIVE_STAR_RATING",
  THUMBS_RATING = "THUMBS_RATING",
}

export enum AuditLogExportStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ERRORED = "ERRORED",
}

export enum EvaluationErrorType {
  AI_CONNECTION_ERROR = "AI_CONNECTION_ERROR",
  TRANSFORMER_ERROR = "TRANSFORMER_ERROR",
  EVALUATION_MODEL_ERROR = "EVALUATION_MODEL_ERROR",
  INVALID_TEST_CASE_PARAMETERS = "INVALID_TEST_CASE_PARAMETERS",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export enum GenerationMode {
  AI_CONNECTION = "AI_CONNECTION",
  PROMPT = "PROMPT",
}

export enum IngestionDataModel {
  TRACE = "TRACE",
  SPAN = "SPAN",
  THREAD = "THREAD",
}

export enum InvitationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
}

export enum Level {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum MetricAlgorithm {
  DEFAULT = "DEFAULT",
  DAG = "DAG",
  GEVAL = "GEVAL",
  JEVAL = "JEVAL",
  CODE = "CODE",
}

export enum MetricEvaluationParam {
  INPUT = "input",
  ACTUALOUTPUT = "actualOutput",
  EXPECTEDOUTPUT = "expectedOutput",
  CONTEXT = "context",
  EXPECTEDTOOLS = "expectedTools",
  CONTENT = "content",
  ROLE = "role",
  SCENARIO = "scenario",
  EXPECTEDOUTCOME = "expectedOutcome",
  TURNS = "turns",
  TOOLSCALLED = "toolsCalled",
  RETRIEVALCONTEXT = "retrievalContext",
  METADATA = "metadata",
  TAGS = "tags",
}

export enum ModelProvider {
  OPEN_AI = "OPEN_AI",
  CUSTOM = "CUSTOM",
  CONFIDENT_AI = "CONFIDENT_AI",
  BEDROCK = "BEDROCK",
  ANTHROPIC = "ANTHROPIC",
  GEMINI = "GEMINI",
  X_AI = "X_AI",
  DEEPSEEK = "DEEPSEEK",
  MOONSHOT_AI = "MOONSHOT_AI",
  VERTEX_AI = "VERTEX_AI",
  AZURE = "AZURE",
  MISTRAL = "MISTRAL",
  PERPLEXITY = "PERPLEXITY",
  OPEN_ROUTER = "OPEN_ROUTER",
  PORTKEY = "PORTKEY",
  LITE_LLM = "LITE_LLM",
  TRUE_FOUNDRY = "TRUE_FOUNDRY",
  HUGGING_FACE = "HUGGING_FACE",
  TYPE_SAFE = "TYPE_SAFE",
  FAL = "FAL",
}

export enum ModelType {
  EVALUATION = "EVALUATION",
  PLATFORM = "PLATFORM",
  GENERATION = "GENERATION",
  SIMULATION = "SIMULATION",
  TEXT_TO_SPEECH = "TEXT_TO_SPEECH",
  SPEECH_TO_TEXT = "SPEECH_TO_TEXT",
  DECISION = "DECISION",
  SPEECH_TO_SPEECH = "SPEECH_TO_SPEECH",
}

export enum PromptType {
  TEXT = "TEXT",
  LIST = "LIST",
}

export enum ScheduleIntervalUnit {
  MINUTE = "MINUTE",
  HOUR = "HOUR",
  DAY = "DAY",
  WEEK = "WEEK",
  MONTH = "MONTH",
}

export enum ScheduleRecurrenceType {
  ONCE = "ONCE",
  INTERVAL = "INTERVAL",
}

export enum SpanType {
  SPAN = "SPAN",
  AGENT = "AGENT",
  TOOL = "TOOL",
  RETRIEVER = "RETRIEVER",
  LLM = "LLM",
}

export enum ToolCallType {
  FUNCTION = "FUNCTION",
  MCP = "MCP",
}

export enum TraceSpanStatus {
  SUCCESS = "SUCCESS",
  ERRORED = "ERRORED",
}

export enum TurnRole {
  USER = "user",
  ASSISTANT = "assistant",
}

export enum WidgetAggregation {
  AVG_COST = "AVG_COST",
  AVG_COST_PER_USER = "AVG_COST_PER_USER",
  AVG_LATENCY = "AVG_LATENCY",
  AVG_RATING = "AVG_RATING",
  AVG_SCORE = "AVG_SCORE",
  AVG_VALUE = "AVG_VALUE",
  COUNT = "COUNT",
  ERROR_COUNT = "ERROR_COUNT",
  ERROR_RATE = "ERROR_RATE",
  FAILURE_RATE = "FAILURE_RATE",
  INPUT_COST = "INPUT_COST",
  INPUT_TOKENS = "INPUT_TOKENS",
  MEDIAN_SCORE = "MEDIAN_SCORE",
  NEW_USERS = "NEW_USERS",
  OUTPUT_COST = "OUTPUT_COST",
  OUTPUT_TOKENS = "OUTPUT_TOKENS",
  P50_LATENCY = "P50_LATENCY",
  P90_LATENCY = "P90_LATENCY",
  P99_LATENCY = "P99_LATENCY",
  PASS_RATE = "PASS_RATE",
  RETENTION = "RETENTION",
  TOTAL_COST = "TOTAL_COST",
  TOTAL_TOKENS = "TOTAL_TOKENS",
  UNIQUE_END_USERS = "UNIQUE_END_USERS",
  UNIQUE_METADATA_VALUES = "UNIQUE_METADATA_VALUES",
  UNIQUE_THREADS = "UNIQUE_THREADS",
  UNIQUE_USERS = "UNIQUE_USERS",
}

export enum WidgetBucketMode {
  SERIES = "SERIES",
  RANGE = "RANGE",
}

export enum WidgetDataModel {
  TRACE = "TRACE",
  SPAN = "SPAN",
  LLM_SPAN = "LLM_SPAN",
  AGENT_SPAN = "AGENT_SPAN",
  RETRIEVER_SPAN = "RETRIEVER_SPAN",
  TOOL_SPAN = "TOOL_SPAN",
  CUSTOM_SPAN = "CUSTOM_SPAN",
  THREAD = "THREAD",
  END_USER = "END_USER",
  METRIC_DATA = "METRIC_DATA",
  ANNOTATION = "ANNOTATION",
  CLASSIFICATION = "CLASSIFICATION",
}

export enum WidgetDimension {
  PROJECT = "project",
  TRACE_NAME = "trace_name",
  SPAN_NAME = "span_name",
  MODEL = "model",
  TYPE = "type",
  THREAD_ID = "thread_id",
  TEST_CASE_ID = "test_case_id",
  TEST_RUN_ID = "test_run_id",
  END_USER = "end_user",
  CUSTOMER = "customer",
  SOURCE = "source",
  ANNOTATOR = "annotator",
  NAME = "name",
  ERROR = "error",
  PROMPT_ALIAS = "prompt_alias",
  TAG = "tag",
  LABEL = "label",
  EVALUATION_MODEL = "evaluation_model",
  PROMPT_VERSION = "prompt_version",
  PROMPT_LABEL = "prompt_label",
  PROMPT_COMMIT_HASH = "prompt_commit_hash",
  METADATA = "metadata",
  HYPERPARAMETER = "hyperparameter",
  CLASSIFIER = "classifier",
  POLARITY = "polarity",
  CLASSIFIER_LABEL = "classifier_label",
  VERSION = "version",
  VALUE = "value",
  FAILURE_SUB_MODE = "failure_sub_mode",
}

export enum WidgetGranularity {
  THIRTY_MINUTES = "thirty_minutes",
  HOUR = "hour",
  DAY = "day",
  WEEK = "week",
  MONTH = "month",
}

export enum WidgetLineColor {
  AMBER = "AMBER",
  VIOLET = "VIOLET",
  EMERALD = "EMERALD",
  BLUE = "BLUE",
  PINK = "PINK",
  CYAN = "CYAN",
  ROSE = "ROSE",
  LIME = "LIME",
  TEAL = "TEAL",
  ORANGE = "ORANGE",
}

export enum WidgetMode {
  TIME_SERIES = "TIME_SERIES",
  DIMENSION_SERIES = "DIMENSION_SERIES",
}

export enum WidgetType {
  LINE = "LINE",
  AREA = "AREA",
  BAR = "BAR",
  STACKED_BAR = "STACKED_BAR",
  GROUPED_BAR = "GROUPED_BAR",
  TABLE = "TABLE",
  BIG_NUMBER = "BIG_NUMBER",
}

export enum WidgetUnit {
  COUNT = "COUNT",
  PERCENT = "PERCENT",
  SCORE = "SCORE",
  SECONDS = "SECONDS",
  USD = "USD",
  MILLISECONDS = "MILLISECONDS",
}

export interface UserReference {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
}

export interface AnnotationSummary {
  id: string;
  fieldType: AnnotationFieldType;
  value: string | number | boolean | string[] | null;
  name: string | null;
  explanation: string | null;
  expectedOutcome: string | null;
  expectedOutput: string | null;
  createdAt: string;
  user: UserReference | null;
}

export interface ApiKey {
  id: number;
  name: string | null;
  valid: boolean;
  created_at: string;
  expiresAt: string | null;
  value: string;
  shadowValue: string | null;
  rotatesAt: string | null;
  lastUsed: string | null;
}

export interface ApiKeyList {
  apiKeys: ApiKey[];
}

export interface ApiKeyRef {
  id: number;
}

export interface AuditLogExport {
  id: string;
  projectId: string | null;
  organizationId: string;
  userId: string;
  status: AuditLogExportStatus;
  exportType:
    | "TRACES"
    | "TRACES_WITH_SPANS"
    | "CONVERSATIONS"
    | "CONVERSATION_METRICS"
    | "ANNOTATIONS"
    | "TEST_RUNS"
    | "AUDIT_LOGS";
  startTime: string | null;
  endTime: string | null;
  rowCount: number | null;
  errorMessage: string | null;
  createdAt: string;
  completedAt: string | null;
}

export interface Classification {
  label: string;
  reason: string;
}

export interface CreateApiKeyRequest {
  name: string;
  expiresInDays?: number;
}

export interface CreateAuditLogExportRequest {
  startTime?: string;
  endTime?: string;
  searchTerm?: string;
}

export interface Rubric {
  scoreRange: [number, number];
  expectedOutcome: string;
}

export interface MetricDag {
  nodes: Record<string, unknown>;
}

export interface JevNoulQuestion {
  type: "noul";
  question: string;
  weight?: number;
  trueDescription?: string;
  falseDescription?: string;
}

export interface JevScoreQuestion {
  type: "score";
  question: string;
  weight?: number;
  levels: string[];
}

export interface JevChoiceQuestion {
  type: "choice";
  question: string;
  weight?: number;
  options: Record<string, number | null>;
}

export type JevQuestion =
  JevNoulQuestion | JevScoreQuestion | JevChoiceQuestion;

export interface CreateMetricRequest {
  name: string;
  multiTurn?: boolean;
  criteria?: string;
  evaluationSteps?: string[];
  evaluationParams?: MetricEvaluationParam[];
  rubric?: Rubric[];
  algorithm?: MetricAlgorithm;
  dag?: MetricDag;
  questions?: JevQuestion[];
}

export interface CreateOrUpdatePolicyRequest {
  name: string;
  description?: string | null;
  permissionIds: string[];
}

export interface CreateOrUpdateRoleRequest {
  name: string;
  description?: string | null;
  policyIds: string[];
}

export interface WidgetTopK {
  limit?: number;
  orderBy?:
    | "count"
    | "avg_latency"
    | "p50_latency"
    | "p90_latency"
    | "p99_latency"
    | "error_rate"
    | "pass_rate"
    | "failure_rate"
    | "input_cost"
    | "output_cost"
    | "total_cost"
    | "avg_cost"
    | "input_tokens"
    | "output_tokens"
    | "total_tokens"
    | "count_distinct_endUserId"
    | "count_distinct_threadId"
    | "count_distinct_model"
    | "count_distinct_projectId"
    | "count_distinct_error"
    | "count_distinct_metadata"
    | "error_count"
    | "pass_count"
    | "avg_score"
    | "stddev_score"
    | "median_score"
    | "avg_rating"
    | "avg_value"
    | "score_histogram"
    | "created_at"
    | "start_time"
    | "dimension";
  direction?: "asc" | "desc";
}

export interface WidgetLayout {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface FilterSetGroupFilter {
  category:
    | "User Id"
    | "Customer Id"
    | "Customer Name"
    | "Thread Id"
    | "Trace UUID"
    | "Trace Name"
    | "Trace Version"
    | "Trace Status"
    | "Trace Tags"
    | "Trace"
    | "Span UUID"
    | "Name"
    | "Span Name"
    | "Span Type"
    | "Span Status"
    | "Metrics Status"
    | "Error Status"
    | "Called tool"
    | "Handed off to"
    | "Handed off by"
    | "Nearest parent of type"
    | "Anywhere under"
    | "Top level"
    | "Model"
    | "Provider"
    | "Integration"
    | "Input argument"
    | "Embedder"
    | "Chunk Size"
    | "Top-K"
    | "Hyperparameter"
    | "Dataset"
    | "Dataset Name"
    | "Test Run ID"
    | "Identifier"
    | "Test File"
    | "Status"
    | "Official"
    | "Evals Mode"
    | "Tests Passed"
    | "Tests Failed"
    | "Pass Rate"
    | "Fail Rate"
    | "Star Rating"
    | "Thumbs Rating"
    | "Explanation"
    | "Expected Output"
    | "Expected Outcome"
    | "Annotator"
    | "End User"
    | "Annotation Type"
    | "Annotation Name"
    | "Annotation Date"
    | "Annotation Rating"
    | "Annotation Thumbs"
    | "Annotation Choice"
    | "Annotation Yes / No"
    | "Annotation Text"
    | "Metric Score"
    | "Metric Status"
    | "Metadata"
    | "Classifier"
    | "Metric"
    | "Metric Name"
    | "Trace Count"
    | "Test Case ID"
    | "Requested review from"
    | "Assigned to"
    | "Tags"
    | "Labels"
    | "Tools Called"
    | "Finalized"
    | "Golden ID"
    | "Ingestion Task"
    | "Latency"
    | "Environment"
    | "Review flag"
    | "Vulnerability"
    | "Vulnerability Type"
    | "Attack Method"
    | "Risk Category"
    | "Framework"
    | "Assessment ID"
    | "Prompt Alias"
    | "Prompt Version"
    | "Prompt Label"
    | "Prompt Commit Hash"
    | "Prompt"
    | "Annotations"
    | "Failure Mode"
    | "Recommended"
    | "Sub-mode Name"
    | "Sub-mode Recommended"
    | "Sub-mode Certainty"
    | "Status Code"
    | "Actor Type";
  condition:
    | "Is less than"
    | "Is equal or less than"
    | "Is greater than"
    | "Is equal or greater than"
    | "Is equal to"
    | "Does not equal"
    | "Has"
    | "Has not"
    | "Is"
    | "Is not"
    | "Is one of"
    | "Is not one of"
    | "Is empty"
    | "Is not empty"
    | "Contains"
    | "Does not contain"
    | "Contains only"
    | "Has decreased by more than"
    | "Has decreased by less than"
    | "Has increased by more than"
    | "Has increased by less than"
    | "Has changed from"
    | "Is between";
  value: string | number | string[];
  key?: string;
}

export interface FilterSetGroup {
  operator: "AND" | "OR";
  filters: FilterSetGroupFilter[];
}

export interface FilterSet {
  operator: "AND" | "OR";
  groups: FilterSetGroup[];
}

export interface WidgetLineExtraQueryParams {}

export interface WidgetLineConfig {
  name: string;
  color?: WidgetLineColor | null;
  dataModel?: WidgetDataModel | null;
  aggregation?: WidgetAggregation | null;
  filters?: FilterSet | null;
  extraQueryParams?: WidgetLineExtraQueryParams | null;
}

export interface CreateWidgetRequest {
  name: string;
  description?: string | null;
  type?: WidgetType | null;
  unit?: WidgetUnit | null;
  mode?: WidgetMode | null;
  bucketMode?: WidgetBucketMode | null;
  dimension?: WidgetDimension | null;
  topK?: WidgetTopK | null;
  startTime?: string | null;
  endTime?: string | null;
  layout?: WidgetLayout | null;
  lines?: WidgetLineConfig[] | null;
}

export interface CreatedApiKey {
  id: number;
  name: string | null;
  valid: boolean;
  created_at: string;
  expiresAt: string | null;
  value: string;
  shadowValue: null | null;
  rotatesAt: null | null;
  lastUsed: null | null;
}

export interface ErrorResponseDetails {
  usage?: string;
  limit?: string;
}

export interface ErrorResponse {
  success: false;
  error: string;
  link?: string;
  deprecated?: boolean;
  details?: ErrorResponseDetails;
}

export interface GovernancePolicyReference {
  id: string;
  name: string;
}

export interface ImmediatelyRotatedApiKey {
  id: number;
  name: string | null;
  valid: boolean;
  created_at: string;
  expiresAt: string | null;
  value: string;
  shadowValue: null | null;
  rotatesAt: null | null;
  lastUsed: string | null;
}

export interface InvitationRef {
  id: number;
}

export interface MLLMImage {
  url: string;
  local: boolean;
  base64?: string;
  filename?: string;
  mimeType?: string;
  dataBase64?: string;
}

export interface MemberRef {
  id: string;
}

export interface MemberRole {
  id: string;
  name: string;
}

export interface Metric {
  id: string;
  name: string;
  algorithm: MetricAlgorithm | null;
  criteria: string | null;
  evaluationSteps: string[] | null;
  rubric: Rubric[] | null;
  dag: MetricDag | null;
  questions: JevQuestion[] | null;
  multiTurn: boolean;
  requiredParameters: MetricEvaluationParam[];
}

export interface MetricData {
  id: string;
  name: string;
  score: number | null;
  reason: string | null;
  success: boolean | null;
  threshold: number | null;
  strictMode: boolean;
  skipped: boolean;
  flaky: boolean;
  evaluationModel: string | null;
  evaluationCost: number | null;
  error: string | null;
  errorType: EvaluationErrorType | null;
  createdAt: string;
  evaluatedAt: string | null;
  multiTurn: boolean;
  traceUuid: string | null;
  spanUuid: string | null;
  threadId: string | null;
  testCaseId: string | null;
  testRunId: string | null;
}

export interface MetricList {
  metrics: Metric[];
}

export interface Model {
  id: string;
  type: ModelType;
  provider: ModelProvider | null;
  name: string | null;
  maxConcurrency: number | null;
  maxInputTokens: number | null;
  modelCredentialId: string | null;
  projectId: string | null;
  organizationId: string | null;
}

export interface ModelCredentials {
  id: string;
  openAiApiKey: string | null;
  anthropicApiKey: string | null;
  geminiApiKey: string | null;
  xAiApiKey: string | null;
  deepSeekApiKey: string | null;
  mistralApiKey: string | null;
  perplexityApiKey: string | null;
  typeSafeApiKey: string | null;
  falApiKey: string | null;
  bedrockModelConfig: Record<string, unknown> | null;
  vertexAiModelConfig: Record<string, unknown> | null;
  azureModelConfig: Record<string, unknown> | null;
  portKeyConfig: Record<string, unknown> | null;
  openRouterConfig: Record<string, unknown> | null;
  trueFoundryConfig: Record<string, unknown> | null;
  liteLlmConfig: Record<string, unknown> | null;
  huggingFaceConfig: Record<string, unknown> | null;
  organizationId: string | null;
}

export interface PendingRotationApiKey {
  id: number;
  name: string | null;
  valid: boolean;
  created_at: string;
  expiresAt: string | null;
  value: string;
  shadowValue: string;
  rotatesAt: string;
  lastUsed: string | null;
}

export interface Permission {
  id: string;
  name: string;
  description: string | null;
}

export interface PermissionList {
  permissions: Permission[];
}

export interface PolicyPermission {
  id: string;
  name: string;
}

export interface Policy {
  id: string;
  name: string;
  description: string | null;
  permissions: PolicyPermission[];
}

export interface PolicyList {
  policies: Policy[];
}

export interface PolicyRef {
  id: string;
}

export interface RolePolicy {
  id: string;
  name: string;
}

export interface RoleRef {
  id: string;
}

export interface RotateApiKeyRequest {
  gracePeriodInHours?: number;
  expiresInDays?: number | null;
}

export interface ToolCall {
  name: string;
  type?: ToolCallType;
  description?: string;
  inputParameters?: Record<string, unknown> | null;
  output?: unknown;
  reasoning?: string;
}

export interface Span {
  uuid: string;
  traceUuid: string;
  parentUuid: string | null;
  name: string | null;
  type: SpanType;
  status: TraceSpanStatus;
  startTime: string;
  endTime: string;
  error: string | null;
  integration: string | null;
  provider: string | null;
  model: string | null;
  endpoint: string | null;
  cost: number | null;
  inputTokenCost: number | null;
  outputTokenCost: number | null;
  costPerInputToken: number | null;
  costPerOutputToken: number | null;
  inputTokenCount: number | null;
  outputTokenCount: number | null;
  promptAlias: string | null;
  promptVersion: string | null;
  promptLabel: string | null;
  promptCommitHash: string | null;
  embedder: string | null;
  topK: number | null;
  chunkSize: number | null;
  description: string | null;
  agentHandoffs: string[] | null;
  availableTools: string[] | null;
  metadata: Record<string, unknown> | null;
  metricCollectionName: string | null;
  input: string | null;
  output: string | null;
  expectedOutput: string | null;
  retrievalContext: string[] | null;
  context: string[] | null;
  toolsCalled: ToolCall[] | null;
  expectedTools: ToolCall[] | null;
  metricsData: MetricData[];
  annotations: AnnotationSummary[];
}

export interface Trace {
  uuid: string;
  name: string | null;
  status: TraceSpanStatus;
  startTime: string;
  endTime: string;
  latency: number;
  cost: number | null;
  threadId: string | null;
  userId: string | null;
  customerId: string | null;
  environment: string;
  tags: string[] | null;
  metadata: Record<string, unknown> | null;
  input: string | null;
  output: string | null;
  expectedOutput: string | null;
  retrievalContext: string[] | null;
  context: string[] | null;
  toolsCalled: ToolCall[] | null;
  expectedTools: ToolCall[] | null;
  testCaseId: string | null;
  metricCollectionName: string | null;
  labels: Record<string, Classification>;
  spans?: Span[];
  metricsData: MetricData[];
  annotations: AnnotationSummary[];
}

export interface Turn {
  id?: string;
  role: TurnRole;
  content: string;
  userId?: string;
  retrievalContext?: string[] | null;
  toolsCalled?: ToolCall[] | null;
}

export interface UpdateApiKeyRequest {
  valid: boolean;
}

export interface UpdateMemberRoleRequest {
  roleId: string;
}

export interface UpdateModelCredentialsRequest {
  provider: ModelProvider;
  apiKey?: string | null;
  modelConfig?: Record<string, unknown> | null;
}

export interface WidgetScalarValue {
  key: string;
  name: string;
  color: WidgetLineColor;
  lineId?: string;
  value: number | null;
}

export interface WidgetBigNumberData {
  kind: "BIG_NUMBER";
  unit: WidgetUnit | null;
  values: WidgetScalarValue[];
}

export interface WidgetSeriesPoint {
  x: string;
  y: number | null;
}

export interface WidgetSeries {
  key: string;
  name: string;
  color: WidgetLineColor;
  lineId?: string;
  points: WidgetSeriesPoint[];
}

export interface WidgetDimensionData {
  kind: "DIMENSION";
  unit: WidgetUnit | null;
  series: WidgetSeries[];
}

export interface WidgetTableColumn {
  key: string;
  label: string;
}

export interface WidgetTableData {
  kind: "TABLE";
  columns: WidgetTableColumn[];
  rows: Record<string, string | number | null>[];
}

export interface WidgetTimeSeriesData {
  kind: "TIME_SERIES";
  unit: WidgetUnit | null;
  series: WidgetSeries[];
}

export type RotatedApiKey = ImmediatelyRotatedApiKey | PendingRotationApiKey;

export type WidgetData =
  | WidgetBigNumberData
  | WidgetTimeSeriesData
  | WidgetDimensionData
  | WidgetTableData;
