// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: annotation-queues).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  FilterSet,
  IngestionDataModel,
  MLLMImage,
  UserReference,
} from "../common/types";

export enum AnnotationQueueType {
  TRACE = "TRACE",
  SPAN = "SPAN",
  THREAD = "THREAD",
  GOLDEN = "GOLDEN",
  TEST_RUN = "TEST_RUN",
}

export enum AssignmentStrategy {
  SINGLE_USER = "SINGLE_USER",
  ROUND_ROBIN = "ROUND_ROBIN",
  RANDOM = "RANDOM",
}

export enum QueueItemStatus {
  IN_PROGRESS = "IN_PROGRESS",
  DRAFT = "DRAFT",
  DEFERRED = "DEFERRED",
  COMPLETED = "COMPLETED",
}

export interface AddSpanQueueItemsRequest {
  spanUuids: string[];
}

export interface AddThreadQueueItemsRequest {
  threadIds: string[];
}

export interface AddTraceQueueItemsRequest {
  traceUuids: string[];
}

export interface AddedQueueItems {
  ids: string[];
}

export interface QueueItemAnnotation {
  fieldType?: "THUMBS_RATING" | "FIVE_STAR_RATING";
  value: boolean | number;
  name?: string;
  explanation?: string;
  expectedOutput?: string;
  expectedOutcome?: string;
  imagesMapping?: Record<string, MLLMImage>;
}

export interface QueueItemFormResponse {
  label: string;
  value?: unknown;
}

export interface AnnotateQueueItemRequest {
  annotations?: QueueItemAnnotation[];
  formResponses?: QueueItemFormResponse[];
  annotatorEmail?: string;
  flagged?: boolean;
  markAsCompleted?: boolean;
}

export interface AnnotateQueueItemResult {
  annotationIds: string[];
  formResponseIds: string[];
}

export interface AssignmentBreakdownEntry {
  assigned: number;
  completed: number;
}

export interface AnnotationQueue {
  id: string;
  name: string;
  type: AnnotationQueueType;
  createdAt: string;
  updatedAt: string;
  testRunId: string | null;
  formId: string | null;
  tags: string[];
  totalItems: number;
  completedItems: number;
  pendingItems: number;
  completionPercentage: number;
  assignedItems: number;
  assignmentBreakdown: Record<string, AssignmentBreakdownEntry>;
}

export interface AnnotationQueueItem {
  id: string;
  traceUuid: string | null;
  spanUuid: string | null;
  threadId: string | null;
  testCaseId: string | null;
  addedAt: string;
  status: QueueItemStatus;
  assignedToEmail: string | null;
}

export interface AnnotationQueueItemList {
  items: AnnotationQueueItem[];
  totalAnnotationQueueItems: number;
  page: number;
  pageSize: number;
}

export interface AnnotationQueueSummary {
  id: string;
  name: string;
  type: AnnotationQueueType;
  createdAt: string;
  updatedAt: string;
  testRunId: string | null;
  formId: string | null;
  tags: string[];
  totalItems: number;
  completedItems: number;
  pendingItems: number;
  completionPercentage: number;
}

export interface AnnotationQueueList {
  annotationQueues: AnnotationQueueSummary[];
  totalAnnotationQueues: number;
  page: number;
  pageSize: number;
}

export interface AnnotationQueueRef {
  id: string;
}

export interface BatchAnnotateFailure {
  queueItemId: string;
  success: false;
  error: string;
}

export interface BatchAnnotateItem {
  queueItemId: string;
  annotations?: QueueItemAnnotation[];
  formResponses?: QueueItemFormResponse[];
  annotatorEmail?: string;
  flagged?: boolean;
  markAsCompleted?: boolean;
}

export interface BatchAnnotateRequest {
  annotatorEmail?: string;
  markAsCompleted?: boolean;
  items: BatchAnnotateItem[];
}

export interface BatchAnnotateSuccess {
  queueItemId: string;
  success: true;
  annotationIds: string[];
  formResponseIds: string[];
}

export interface BatchAnnotateResult {
  results: (BatchAnnotateSuccess | BatchAnnotateFailure)[];
}

export interface CreateAnnotationQueueRequest {
  name: string;
  type: AnnotationQueueType;
  formId?: string;
  tags?: string[];
}

export interface CreateQueueIngestionTaskRequest {
  name: string;
  dataModel: IngestionDataModel;
  description?: string | null;
  enabled?: boolean;
  sampleRate?: number;
  filters?: FilterSet;
  maxItems?: number | null;
  assignmentStrategy?: AssignmentStrategy;
  reviewerEmails?: string[];
}

export interface QueueIngestionTask {
  id: string;
  annotationQueueId: string | null;
  name: string;
  description: string | null;
  enabled: boolean;
  sampleRate: number;
  dataModel: IngestionDataModel;
  filters: FilterSet | null;
  maxItems: number | null;
  assignmentStrategy: AssignmentStrategy;
  reviewers: UserReference[];
  createdAt: string;
  updatedAt: string;
}

export interface QueueIngestionTaskSummary {
  id: string;
  name: string;
  enabled: boolean;
  dataModel: IngestionDataModel;
}

export interface QueueIngestionTaskList {
  queueIngestionTasks: QueueIngestionTaskSummary[];
}

export interface QueueIngestionTaskRef {
  id: string;
}

export interface UpdateAnnotationQueueRequest {
  name?: string;
  formId?: string | null;
  tags?: string[];
}

export interface UpdateQueueIngestionTaskRequest {
  name?: string;
  dataModel?: IngestionDataModel;
  newAnnotationQueueId?: string | null;
  description?: string | null;
  enabled?: boolean;
  sampleRate?: number;
  filters?: FilterSet;
  maxItems?: number | null;
  assignmentStrategy?: AssignmentStrategy;
  reviewerEmails?: string[];
}

export type AddQueueItemsRequest =
  | AddTraceQueueItemsRequest
  | AddSpanQueueItemsRequest
  | AddThreadQueueItemsRequest;
