// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: threads).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import { Thread, ThreadList, ThreadSortBy } from "./types";

export class ThreadsClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Threads
   *
   * Lists the threads in your Confident AI project one page at a time, most
   * recently active first by default. Each thread is returned as a summary;
   * retrieve a thread by id for its traces, evaluation results and annotations.
   *
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   * @param cursor This is used for pagination, and should be set to the
   *   `nextCursor` value returned in the previous response to get the next page
   *   of results.
   * @param start This filters for results created at or after the specified
   *   start datetime, in ISO 8601 format. Defaults to 60 days ago.
   * @param end This filters for results created before the specified end
   *   datetime, in ISO 8601 format. Defaults to the current time.
   * @param ascending This determines if the field specified in `sortBy` should
   *   be in ascending order. Defaults to `false`, which returns the newest
   *   results first.
   * @param sortBy This determines the field to sort by. Defaults to
   *   `lastActivity`.
   * @param environment This filters the threads by the environment where their
   *   traces were created, and returns threads from all environments if not
   *   specified.
   */
  async list(
    options: {
      pageSize?: number;
      cursor?: string;
      start?: string;
      end?: string;
      ascending?: "true" | "false";
      sortBy?: ThreadSortBy;
      environment?: string;
    } = {},
  ): Promise<ThreadList> {
    const { pageSize, cursor, start, end, ascending, sortBy, environment } =
      options;
    return this.api.sendRequest<ThreadList>(
      HttpMethods.GET,
      Endpoints.THREADS_ENDPOINT,
      {
        params: {
          pageSize,
          cursor,
          start,
          end,
          ascending,
          sortBy,
          environment,
        },
      },
    );
  }

  /**
   * Get Thread
   *
   * Retrieves a thread by id from your Confident AI project, with its
   * evaluation results, annotations and the first 100 traces of the
   * conversation, oldest first.
   *
   * @param threadId The id of the thread, as you supplied it when creating its
   *   traces.
   */
  async get(threadId: string): Promise<Thread> {
    return this.api.sendRequest<Thread>(
      HttpMethods.GET,
      Endpoints.THREAD_ENDPOINT,
      { urlParams: { threadId } },
    );
  }
}
