// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: test-runs).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { EvaluationErrorType, ToolCall, Turn } from "../common/types";

export enum TestCaseResultStatus {
  ACCEPTED = "accepted",
  ALREADY_RECEIVED = "already_received",
}

export enum TestRunStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ERRORED = "ERRORED",
  CANCELLED = "CANCELLED",
}

export interface SummaryOverview {
  summary: string[];
  actionItems: string[];
}

export interface SummaryPoint {
  content: string;
  testCaseIds: string[];
  grade?: number;
}

export interface TopicSummary {
  topic: string;
  summaryPoints: SummaryPoint[];
  testCaseIds: string[];
}

export interface AiInsightsSummary {
  summaryOverview: SummaryOverview;
  topicSummaries: TopicSummary[];
}

export interface CreateTestRunRequest {
  metricCollection?: string;
  identifier?: string;
}

export interface MetricScores {
  metric: string;
  scores: number[];
  passes: number;
  fails: number;
  errors: number;
  errorType: EvaluationErrorType | null;
}

export interface SubmitTestCaseResultRequest {
  actualOutput?: string;
  retrievalContext?: string[];
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  tokenCost?: number;
  inputTokenCount?: number;
  outputTokenCount?: number;
  metadata?: Record<string, unknown>;
}

export interface SubmittedTestCaseResult {
  testCaseId: string;
  status: TestCaseResultStatus;
}

export interface TestCaseMetricData {
  id: string;
  name: string;
  score: number | null;
  reason: string | null;
  success: boolean | null;
  threshold: number | null;
  strictMode: boolean;
  skipped: boolean;
  flaky: boolean;
  evaluationModel: string | null;
  evaluationCost: number | null;
  error: string | null;
  errorType: EvaluationErrorType | null;
  createdAt: string;
  evaluatedAt: string | null;
  traceUuid: string | null;
  spanUuid: string | null;
}

export interface TestCaseTrace {
  uuid: string;
  name: string | null;
  input: string | null;
  output: string | null;
  startTime: string;
  endTime: string;
  environment: string;
  metadata: Record<string, unknown> | null;
  tags: string[] | null;
  threadId: string | null;
  userId: string | null;
  metricCollectionName: string | null;
  retrievalContext: string[] | null;
  context: string[] | null;
  expectedOutput: string | null;
  toolsCalled: ToolCall[] | null;
  expectedTools: ToolCall[] | null;
}

export interface TestRunSingleTurnTestCase {
  input: string | null;
  actualOutput: string | null;
  expectedOutput: string | null;
  context: string[] | null;
  retrievalContext: string[] | null;
  toolsCalled: ToolCall[] | null;
  expectedTools: ToolCall[] | null;
  id: string;
  name: string;
  success: boolean | null;
  runDuration: number | null;
  evaluationCost: number | null;
  comments: string | null;
  additionalMetadata: Record<string, unknown> | null;
  metricsData: TestCaseMetricData[];
}

export interface TestRunMultiTurnTestCase {
  turns: Turn[];
  scenario: string | null;
  expectedOutcome: string | null;
  userDescription: string | null;
  context: string[] | null;
  id: string;
  name: string;
  success: boolean | null;
  runDuration: number | null;
  evaluationCost: number | null;
  comments: string | null;
  additionalMetadata: Record<string, unknown> | null;
  metricsData: TestCaseMetricData[];
}

export interface TestRunTraceTestCase {
  trace: TestCaseTrace;
  id: string;
  name: string;
  success: boolean | null;
  runDuration: number | null;
  evaluationCost: number | null;
  comments: string | null;
  additionalMetadata: Record<string, unknown> | null;
  metricsData: TestCaseMetricData[];
}

export type TestRunTestCase =
  TestRunSingleTurnTestCase | TestRunMultiTurnTestCase | TestRunTraceTestCase;

export interface TestRun {
  id: string;
  createdAt: string;
  identifier: string | null;
  status: TestRunStatus;
  multiTurn: boolean;
  testsPassed: number;
  testsFailed: number;
  totalTests: number;
  metricsScores: MetricScores[];
  runDuration: number;
  evaluationCost: number | null;
  datasetAlias: string | null;
  testFile: string | null;
  summary: AiInsightsSummary | null;
  testCases: TestRunTestCase[];
}

export interface TestRunSummary {
  id: string;
  createdAt: string;
  identifier: string | null;
  status: TestRunStatus;
  multiTurn: boolean;
  testsPassed: number;
  testsFailed: number;
  totalTests: number;
  metricsScores: MetricScores[];
  runDuration: number;
  evaluationCost: number | null;
  datasetAlias: string | null;
  testFile: string | null;
  summary: AiInsightsSummary | null;
}

export interface TestRunList {
  testRuns: TestRunSummary[];
  totalTestRuns: number;
  page: number;
  pageSize: number;
}

export interface TestRunRef {
  id: string;
}
