// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: spans).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import { Span, SpanType } from "../common/types";
import { SpanList, SpanSortBy } from "./types";

export class SpansClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Spans
   *
   * Lists the spans in your Confident AI project one page at a time, newest
   * first by default, as summary rows. Retrieve a span by id for its full
   * detail.
   *
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   * @param cursor This is used for pagination, and should be set to the
   *   `nextCursor` value returned in the previous response to get the next page
   *   of results.
   * @param start This filters for results created at or after the specified
   *   start datetime, in ISO 8601 format. Defaults to 60 days ago.
   * @param end This filters for results created before the specified end
   *   datetime, in ISO 8601 format. Defaults to the current time.
   * @param ascending This determines if the field specified in `sortBy` should
   *   be in ascending order. Defaults to `false`, which returns the newest
   *   results first.
   * @param sortBy This determines the field to sort by. Defaults to
   *   `createdAt`.
   * @param environment This filters the spans by the environment where their
   *   trace was created, and returns spans from all environments if not
   *   specified.
   * @param type Filter by the specific type of span.
   * @param traceUuid Filter spans that belong to the trace with this uuid.
   * @param name Filter spans by their exact name.
   * @param hasError Filter for spans that either failed (`true`) or succeeded
   *   (`false`).
   * @param model Filter LLM spans by the model used.
   * @param promptAlias This filters the spans by the prompt alias used.
   * @param promptVersion This filters the spans by the prompt version used.
   * @param promptLabel This filters the spans by the prompt label used.
   * @param promptCommitHash This filters the spans by the exact prompt commit
   *   hash used.
   * @param embedder Filter retriever spans by the embedder model used.
   * @param topK Filter retriever spans by the `topK` value.
   * @param chunkSize Filter retriever spans by the chunk size.
   */
  async list(
    options: {
      pageSize?: number;
      cursor?: string;
      start?: string;
      end?: string;
      ascending?: "true" | "false";
      sortBy?: SpanSortBy;
      environment?: string;
      type?: SpanType;
      traceUuid?: string;
      name?: string;
      hasError?: "true" | "false";
      model?: string;
      promptAlias?: string;
      promptVersion?: string;
      promptLabel?: string;
      promptCommitHash?: string;
      embedder?: string;
      topK?: number | null;
      chunkSize?: number | null;
    } = {},
  ): Promise<SpanList> {
    const {
      pageSize,
      cursor,
      start,
      end,
      ascending,
      sortBy,
      environment,
      type,
      traceUuid,
      name,
      hasError,
      model,
      promptAlias,
      promptVersion,
      promptLabel,
      promptCommitHash,
      embedder,
      topK,
      chunkSize,
    } = options;
    return this.api.sendRequest<SpanList>(
      HttpMethods.GET,
      Endpoints.SPANS_ENDPOINT,
      {
        params: {
          pageSize,
          cursor,
          start,
          end,
          ascending,
          sortBy,
          environment,
          type,
          traceUuid,
          name,
          hasError,
          model,
          promptAlias,
          promptVersion,
          promptLabel,
          promptCommitHash,
          embedder,
          topK,
          chunkSize,
        },
      },
    );
  }

  /**
   * Get Span
   *
   * Retrieves a span by uuid from your Confident AI project, with its full
   * input and output, evaluation fields, results and annotations.
   *
   * @param spanUuid The unique identifier of the span.
   */
  async get(spanUuid: string): Promise<Span> {
    return this.api.sendRequest<Span>(
      HttpMethods.GET,
      Endpoints.SPAN_ENDPOINT,
      { urlParams: { spanUuid } },
    );
  }
}
