# @generated by scripts/generate_sdk.py from
# the shapes shared across packages/shared/openapi/openapi.yml.
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Tuple, Union

from pydantic import Field

from confident_ai.types import ConfidentBaseModel


class AnnotationFieldType(Enum):
    TEXT = "TEXT"
    NUMBER = "NUMBER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    CHOICE = "CHOICE"
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE"
    FIVE_STAR_RATING = "FIVE_STAR_RATING"
    THUMBS_RATING = "THUMBS_RATING"


class AuditLogExportStatus(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ERRORED = "ERRORED"


class EvaluationErrorType(Enum):
    AI_CONNECTION_ERROR = "AI_CONNECTION_ERROR"
    TRANSFORMER_ERROR = "TRANSFORMER_ERROR"
    EVALUATION_MODEL_ERROR = "EVALUATION_MODEL_ERROR"
    INVALID_TEST_CASE_PARAMETERS = "INVALID_TEST_CASE_PARAMETERS"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class GenerationMode(Enum):
    AI_CONNECTION = "AI_CONNECTION"
    PROMPT = "PROMPT"


class IngestionDataModel(Enum):
    TRACE = "TRACE"
    SPAN = "SPAN"
    THREAD = "THREAD"


class InvitationStatus(Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"


class Level(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class MetricAlgorithm(Enum):
    DEFAULT = "DEFAULT"
    DAG = "DAG"
    GEVAL = "GEVAL"
    JEVAL = "JEVAL"
    CODE = "CODE"


class MetricEvaluationParam(Enum):
    INPUT = "input"
    ACTUALOUTPUT = "actualOutput"
    EXPECTEDOUTPUT = "expectedOutput"
    CONTEXT = "context"
    EXPECTEDTOOLS = "expectedTools"
    CONTENT = "content"
    ROLE = "role"
    SCENARIO = "scenario"
    EXPECTEDOUTCOME = "expectedOutcome"
    TURNS = "turns"
    TOOLSCALLED = "toolsCalled"
    RETRIEVALCONTEXT = "retrievalContext"
    METADATA = "metadata"
    TAGS = "tags"


class ModelProvider(Enum):
    OPEN_AI = "OPEN_AI"
    CUSTOM = "CUSTOM"
    CONFIDENT_AI = "CONFIDENT_AI"
    BEDROCK = "BEDROCK"
    ANTHROPIC = "ANTHROPIC"
    GEMINI = "GEMINI"
    X_AI = "X_AI"
    DEEPSEEK = "DEEPSEEK"
    MOONSHOT_AI = "MOONSHOT_AI"
    VERTEX_AI = "VERTEX_AI"
    AZURE = "AZURE"
    MISTRAL = "MISTRAL"
    PERPLEXITY = "PERPLEXITY"
    OPEN_ROUTER = "OPEN_ROUTER"
    PORTKEY = "PORTKEY"
    LITE_LLM = "LITE_LLM"
    TRUE_FOUNDRY = "TRUE_FOUNDRY"
    HUGGING_FACE = "HUGGING_FACE"
    TYPE_SAFE = "TYPE_SAFE"
    FAL = "FAL"


class ModelType(Enum):
    EVALUATION = "EVALUATION"
    PLATFORM = "PLATFORM"
    GENERATION = "GENERATION"
    SIMULATION = "SIMULATION"
    TEXT_TO_SPEECH = "TEXT_TO_SPEECH"
    SPEECH_TO_TEXT = "SPEECH_TO_TEXT"
    DECISION = "DECISION"
    SPEECH_TO_SPEECH = "SPEECH_TO_SPEECH"


class PromptType(Enum):
    TEXT = "TEXT"
    LIST = "LIST"


class ScheduleIntervalUnit(Enum):
    MINUTE = "MINUTE"
    HOUR = "HOUR"
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"


class ScheduleRecurrenceType(Enum):
    ONCE = "ONCE"
    INTERVAL = "INTERVAL"


class SpanType(Enum):
    SPAN = "SPAN"
    AGENT = "AGENT"
    TOOL = "TOOL"
    RETRIEVER = "RETRIEVER"
    LLM = "LLM"


class ToolCallType(Enum):
    FUNCTION = "FUNCTION"
    MCP = "MCP"


class TraceSpanStatus(Enum):
    SUCCESS = "SUCCESS"
    ERRORED = "ERRORED"


class TurnRole(Enum):
    USER = "user"
    ASSISTANT = "assistant"


class WidgetAggregation(Enum):
    AVG_COST = "AVG_COST"
    AVG_COST_PER_USER = "AVG_COST_PER_USER"
    AVG_LATENCY = "AVG_LATENCY"
    AVG_RATING = "AVG_RATING"
    AVG_SCORE = "AVG_SCORE"
    AVG_VALUE = "AVG_VALUE"
    COUNT = "COUNT"
    ERROR_COUNT = "ERROR_COUNT"
    ERROR_RATE = "ERROR_RATE"
    FAILURE_RATE = "FAILURE_RATE"
    INPUT_COST = "INPUT_COST"
    INPUT_TOKENS = "INPUT_TOKENS"
    MEDIAN_SCORE = "MEDIAN_SCORE"
    NEW_USERS = "NEW_USERS"
    OUTPUT_COST = "OUTPUT_COST"
    OUTPUT_TOKENS = "OUTPUT_TOKENS"
    P50_LATENCY = "P50_LATENCY"
    P90_LATENCY = "P90_LATENCY"
    P99_LATENCY = "P99_LATENCY"
    PASS_RATE = "PASS_RATE"
    RETENTION = "RETENTION"
    TOTAL_COST = "TOTAL_COST"
    TOTAL_TOKENS = "TOTAL_TOKENS"
    UNIQUE_END_USERS = "UNIQUE_END_USERS"
    UNIQUE_METADATA_VALUES = "UNIQUE_METADATA_VALUES"
    UNIQUE_THREADS = "UNIQUE_THREADS"
    UNIQUE_USERS = "UNIQUE_USERS"


class WidgetBucketMode(Enum):
    SERIES = "SERIES"
    RANGE = "RANGE"


class WidgetDataModel(Enum):
    TRACE = "TRACE"
    SPAN = "SPAN"
    LLM_SPAN = "LLM_SPAN"
    AGENT_SPAN = "AGENT_SPAN"
    RETRIEVER_SPAN = "RETRIEVER_SPAN"
    TOOL_SPAN = "TOOL_SPAN"
    CUSTOM_SPAN = "CUSTOM_SPAN"
    THREAD = "THREAD"
    END_USER = "END_USER"
    METRIC_DATA = "METRIC_DATA"
    ANNOTATION = "ANNOTATION"
    CLASSIFICATION = "CLASSIFICATION"


class WidgetDimension(Enum):
    PROJECT = "project"
    TRACE_NAME = "trace_name"
    SPAN_NAME = "span_name"
    MODEL = "model"
    TYPE = "type"
    THREAD_ID = "thread_id"
    TEST_CASE_ID = "test_case_id"
    TEST_RUN_ID = "test_run_id"
    END_USER = "end_user"
    CUSTOMER = "customer"
    SOURCE = "source"
    ANNOTATOR = "annotator"
    NAME = "name"
    ERROR = "error"
    PROMPT_ALIAS = "prompt_alias"
    TAG = "tag"
    LABEL = "label"
    EVALUATION_MODEL = "evaluation_model"
    PROMPT_VERSION = "prompt_version"
    PROMPT_LABEL = "prompt_label"
    PROMPT_COMMIT_HASH = "prompt_commit_hash"
    METADATA = "metadata"
    HYPERPARAMETER = "hyperparameter"
    CLASSIFIER = "classifier"
    POLARITY = "polarity"
    CLASSIFIER_LABEL = "classifier_label"
    VERSION = "version"
    VALUE = "value"
    FAILURE_SUB_MODE = "failure_sub_mode"


class WidgetGranularity(Enum):
    THIRTY_MINUTES = "thirty_minutes"
    HOUR = "hour"
    DAY = "day"
    WEEK = "week"
    MONTH = "month"


class WidgetLineColor(Enum):
    AMBER = "AMBER"
    VIOLET = "VIOLET"
    EMERALD = "EMERALD"
    BLUE = "BLUE"
    PINK = "PINK"
    CYAN = "CYAN"
    ROSE = "ROSE"
    LIME = "LIME"
    TEAL = "TEAL"
    ORANGE = "ORANGE"


class WidgetMode(Enum):
    TIME_SERIES = "TIME_SERIES"
    DIMENSION_SERIES = "DIMENSION_SERIES"


class WidgetType(Enum):
    LINE = "LINE"
    AREA = "AREA"
    BAR = "BAR"
    STACKED_BAR = "STACKED_BAR"
    GROUPED_BAR = "GROUPED_BAR"
    TABLE = "TABLE"
    BIG_NUMBER = "BIG_NUMBER"


class WidgetUnit(Enum):
    COUNT = "COUNT"
    PERCENT = "PERCENT"
    SCORE = "SCORE"
    SECONDS = "SECONDS"
    USD = "USD"
    MILLISECONDS = "MILLISECONDS"


class UserReference(ConfidentBaseModel):
    id: str
    email: str
    name: Optional[str]
    image: Optional[str]


class AnnotationSummary(ConfidentBaseModel):
    id: str
    field_type: AnnotationFieldType = Field(alias="fieldType")
    value: Optional[Union[str, float, bool, List[str]]]
    name: Optional[str]
    explanation: Optional[str]
    expected_outcome: Optional[str] = Field(alias="expectedOutcome")
    expected_output: Optional[str] = Field(alias="expectedOutput")
    created_at: str = Field(alias="createdAt")
    user: Optional[UserReference]


class ApiKey(ConfidentBaseModel):
    id: int
    name: Optional[str]
    valid: bool
    created_at: str
    expires_at: Optional[str] = Field(alias="expiresAt")
    value: str
    shadow_value: Optional[str] = Field(alias="shadowValue")
    rotates_at: Optional[str] = Field(alias="rotatesAt")
    last_used: Optional[str] = Field(alias="lastUsed")


class ApiKeyList(ConfidentBaseModel):
    api_keys: List[ApiKey] = Field(alias="apiKeys")


class ApiKeyRef(ConfidentBaseModel):
    id: int


class AuditLogExport(ConfidentBaseModel):
    id: str
    project_id: Optional[str] = Field(alias="projectId")
    organization_id: str = Field(alias="organizationId")
    user_id: str = Field(alias="userId")
    status: AuditLogExportStatus
    export_type: Literal[
        "TRACES",
        "TRACES_WITH_SPANS",
        "CONVERSATIONS",
        "CONVERSATION_METRICS",
        "ANNOTATIONS",
        "TEST_RUNS",
        "AUDIT_LOGS",
    ] = Field(
        alias="exportType",
    )
    start_time: Optional[str] = Field(alias="startTime")
    end_time: Optional[str] = Field(alias="endTime")
    row_count: Optional[int] = Field(alias="rowCount")
    error_message: Optional[str] = Field(alias="errorMessage")
    created_at: str = Field(alias="createdAt")
    completed_at: Optional[str] = Field(alias="completedAt")


class Classification(ConfidentBaseModel):
    label: str
    reason: str


class CreateApiKeyRequest(ConfidentBaseModel):
    name: str
    expires_in_days: Optional[int] = Field(default=None, alias="expiresInDays")


class CreateAuditLogExportRequest(ConfidentBaseModel):
    start_time: Optional[str] = Field(default=None, alias="startTime")
    end_time: Optional[str] = Field(default=None, alias="endTime")
    search_term: Optional[str] = Field(default=None, alias="searchTerm")


class Rubric(ConfidentBaseModel):
    score_range: Tuple[int, int] = Field(alias="scoreRange")
    expected_outcome: str = Field(alias="expectedOutcome")


class MetricDag(ConfidentBaseModel):
    nodes: Dict[str, Any]


class JevNoulQuestion(ConfidentBaseModel):
    type: Literal["noul"]
    question: str
    weight: Optional[float] = None
    true_description: Optional[str] = Field(
        default=None,
        alias="trueDescription",
    )
    false_description: Optional[str] = Field(
        default=None,
        alias="falseDescription",
    )


class JevScoreQuestion(ConfidentBaseModel):
    type: Literal["score"]
    question: str
    weight: Optional[float] = None
    levels: List[str]


class JevChoiceQuestion(ConfidentBaseModel):
    type: Literal["choice"]
    question: str
    weight: Optional[float] = None
    options: Dict[str, Optional[float]]


JevQuestion = Union[JevNoulQuestion, JevScoreQuestion, JevChoiceQuestion]


class CreateMetricRequest(ConfidentBaseModel):
    name: str
    multi_turn: Optional[bool] = Field(default=None, alias="multiTurn")
    criteria: Optional[str] = None
    evaluation_steps: Optional[List[str]] = Field(
        default=None,
        alias="evaluationSteps",
    )
    evaluation_params: Optional[List[MetricEvaluationParam]] = Field(
        default=None,
        alias="evaluationParams",
    )
    rubric: Optional[List[Rubric]] = None
    algorithm: Optional[MetricAlgorithm] = None
    dag: Optional[MetricDag] = None
    questions: Optional[List[JevQuestion]] = None


class CreateOrUpdatePolicyRequest(ConfidentBaseModel):
    name: str
    description: Optional[str] = None
    permission_ids: List[str] = Field(alias="permissionIds")


class CreateOrUpdateRoleRequest(ConfidentBaseModel):
    name: str
    description: Optional[str] = None
    policy_ids: List[str] = Field(alias="policyIds")


class WidgetTopK(ConfidentBaseModel):
    limit: Optional[int] = None
    order_by: Optional[
        Literal[
            "count",
            "avg_latency",
            "p50_latency",
            "p90_latency",
            "p99_latency",
            "error_rate",
            "pass_rate",
            "failure_rate",
            "input_cost",
            "output_cost",
            "total_cost",
            "avg_cost",
            "input_tokens",
            "output_tokens",
            "total_tokens",
            "count_distinct_endUserId",
            "count_distinct_threadId",
            "count_distinct_model",
            "count_distinct_projectId",
            "count_distinct_error",
            "count_distinct_metadata",
            "error_count",
            "pass_count",
            "avg_score",
            "stddev_score",
            "median_score",
            "avg_rating",
            "avg_value",
            "score_histogram",
            "created_at",
            "start_time",
            "dimension",
        ]
    ] = Field(
        default=None,
        alias="orderBy",
    )
    direction: Optional[Literal["asc", "desc"]] = None


class WidgetLayout(ConfidentBaseModel):
    x: float
    y: float
    w: float
    h: float


class FilterSetGroupFilter(ConfidentBaseModel):
    category: Literal[
        "User Id",
        "Customer Id",
        "Customer Name",
        "Thread Id",
        "Trace UUID",
        "Trace Name",
        "Trace Version",
        "Trace Status",
        "Trace Tags",
        "Trace",
        "Span UUID",
        "Name",
        "Span Name",
        "Span Type",
        "Span Status",
        "Metrics Status",
        "Error Status",
        "Called tool",
        "Handed off to",
        "Handed off by",
        "Nearest parent of type",
        "Anywhere under",
        "Top level",
        "Model",
        "Provider",
        "Integration",
        "Input argument",
        "Embedder",
        "Chunk Size",
        "Top-K",
        "Hyperparameter",
        "Dataset",
        "Dataset Name",
        "Test Run ID",
        "Identifier",
        "Test File",
        "Status",
        "Official",
        "Evals Mode",
        "Tests Passed",
        "Tests Failed",
        "Pass Rate",
        "Fail Rate",
        "Star Rating",
        "Thumbs Rating",
        "Explanation",
        "Expected Output",
        "Expected Outcome",
        "Annotator",
        "End User",
        "Annotation Type",
        "Annotation Name",
        "Annotation Date",
        "Annotation Rating",
        "Annotation Thumbs",
        "Annotation Choice",
        "Annotation Yes / No",
        "Annotation Text",
        "Metric Score",
        "Metric Status",
        "Metadata",
        "Classifier",
        "Metric",
        "Metric Name",
        "Trace Count",
        "Test Case ID",
        "Requested review from",
        "Assigned to",
        "Tags",
        "Labels",
        "Tools Called",
        "Finalized",
        "Golden ID",
        "Ingestion Task",
        "Latency",
        "Environment",
        "Review flag",
        "Vulnerability",
        "Vulnerability Type",
        "Attack Method",
        "Risk Category",
        "Framework",
        "Assessment ID",
        "Prompt Alias",
        "Prompt Version",
        "Prompt Label",
        "Prompt Commit Hash",
        "Prompt",
        "Annotations",
        "Failure Mode",
        "Recommended",
        "Sub-mode Name",
        "Sub-mode Recommended",
        "Sub-mode Certainty",
        "Status Code",
        "Actor Type",
    ]
    condition: Literal[
        "Is less than",
        "Is equal or less than",
        "Is greater than",
        "Is equal or greater than",
        "Is equal to",
        "Does not equal",
        "Has",
        "Has not",
        "Is",
        "Is not",
        "Is one of",
        "Is not one of",
        "Is empty",
        "Is not empty",
        "Contains",
        "Does not contain",
        "Contains only",
        "Has decreased by more than",
        "Has decreased by less than",
        "Has increased by more than",
        "Has increased by less than",
        "Has changed from",
        "Is between",
    ]
    value: Union[str, float, List[str]]
    key: Optional[str] = None


class FilterSetGroup(ConfidentBaseModel):
    operator: Literal["AND", "OR"]
    filters: List[FilterSetGroupFilter]


class FilterSet(ConfidentBaseModel):
    operator: Literal["AND", "OR"]
    groups: List[FilterSetGroup]


class WidgetLineExtraQueryParams(ConfidentBaseModel):
    pass


class WidgetLineConfig(ConfidentBaseModel):
    name: str
    color: Optional[WidgetLineColor] = None
    data_model: Optional[WidgetDataModel] = Field(
        default=None,
        alias="dataModel",
    )
    aggregation: Optional[WidgetAggregation] = None
    filters: Optional[FilterSet] = None
    extra_query_params: Optional[WidgetLineExtraQueryParams] = Field(
        default=None,
        alias="extraQueryParams",
    )


class CreateWidgetRequest(ConfidentBaseModel):
    name: str
    description: Optional[str] = None
    type: Optional[WidgetType] = None
    unit: Optional[WidgetUnit] = None
    mode: Optional[WidgetMode] = None
    bucket_mode: Optional[WidgetBucketMode] = Field(
        default=None,
        alias="bucketMode",
    )
    dimension: Optional[WidgetDimension] = None
    top_k: Optional[WidgetTopK] = Field(default=None, alias="topK")
    start_time: Optional[str] = Field(default=None, alias="startTime")
    end_time: Optional[str] = Field(default=None, alias="endTime")
    layout: Optional[WidgetLayout] = None
    lines: Optional[List[WidgetLineConfig]] = None


class CreatedApiKey(ConfidentBaseModel):
    id: int
    name: Optional[str]
    valid: bool
    created_at: str
    expires_at: Optional[str] = Field(alias="expiresAt")
    value: str
    shadow_value: Optional[Any] = Field(alias="shadowValue")
    rotates_at: Optional[Any] = Field(alias="rotatesAt")
    last_used: Optional[Any] = Field(alias="lastUsed")


class ErrorResponseDetails(ConfidentBaseModel):
    usage: Optional[str] = None
    limit: Optional[str] = None


class ErrorResponse(ConfidentBaseModel):
    success: Literal[False]
    error: str
    link: Optional[str] = None
    deprecated: Optional[bool] = None
    details: Optional[ErrorResponseDetails] = None


class GovernancePolicyReference(ConfidentBaseModel):
    id: str
    name: str


class ImmediatelyRotatedApiKey(ConfidentBaseModel):
    id: int
    name: Optional[str]
    valid: bool
    created_at: str
    expires_at: Optional[str] = Field(alias="expiresAt")
    value: str
    shadow_value: Optional[Any] = Field(alias="shadowValue")
    rotates_at: Optional[Any] = Field(alias="rotatesAt")
    last_used: Optional[str] = Field(alias="lastUsed")


class InvitationRef(ConfidentBaseModel):
    id: int


class MLLMImage(ConfidentBaseModel):
    url: str
    local: bool
    base64: Optional[str] = None
    filename: Optional[str] = None
    mime_type: Optional[str] = Field(default=None, alias="mimeType")
    data_base64: Optional[str] = Field(default=None, alias="dataBase64")


class MemberRef(ConfidentBaseModel):
    id: str


class MemberRole(ConfidentBaseModel):
    id: str
    name: str


class Metric(ConfidentBaseModel):
    id: str
    name: str
    algorithm: Optional[MetricAlgorithm]
    criteria: Optional[str]
    evaluation_steps: Optional[List[str]] = Field(alias="evaluationSteps")
    rubric: Optional[List[Rubric]]
    dag: Optional[MetricDag]
    questions: Optional[List[JevQuestion]]
    multi_turn: bool = Field(alias="multiTurn")
    required_parameters: List[MetricEvaluationParam] = Field(
        alias="requiredParameters",
    )


class MetricData(ConfidentBaseModel):
    id: str
    name: str
    score: Optional[float]
    reason: Optional[str]
    success: Optional[bool]
    threshold: Optional[float]
    strict_mode: bool = Field(alias="strictMode")
    skipped: bool
    flaky: bool
    evaluation_model: Optional[str] = Field(alias="evaluationModel")
    evaluation_cost: Optional[float] = Field(alias="evaluationCost")
    error: Optional[str]
    error_type: Optional[EvaluationErrorType] = Field(alias="errorType")
    created_at: str = Field(alias="createdAt")
    evaluated_at: Optional[str] = Field(alias="evaluatedAt")
    multi_turn: bool = Field(alias="multiTurn")
    trace_uuid: Optional[str] = Field(alias="traceUuid")
    span_uuid: Optional[str] = Field(alias="spanUuid")
    thread_id: Optional[str] = Field(alias="threadId")
    test_case_id: Optional[str] = Field(alias="testCaseId")
    test_run_id: Optional[str] = Field(alias="testRunId")


class MetricList(ConfidentBaseModel):
    metrics: List[Metric]


class Model(ConfidentBaseModel):
    id: str
    type: ModelType
    provider: Optional[ModelProvider]
    name: Optional[str]
    max_concurrency: Optional[int] = Field(alias="maxConcurrency")
    max_input_tokens: Optional[int] = Field(alias="maxInputTokens")
    model_credential_id: Optional[str] = Field(alias="modelCredentialId")
    project_id: Optional[str] = Field(alias="projectId")
    organization_id: Optional[str] = Field(alias="organizationId")


class ModelCredentials(ConfidentBaseModel):
    id: str
    open_ai_api_key: Optional[str] = Field(alias="openAiApiKey")
    anthropic_api_key: Optional[str] = Field(alias="anthropicApiKey")
    gemini_api_key: Optional[str] = Field(alias="geminiApiKey")
    x_ai_api_key: Optional[str] = Field(alias="xAiApiKey")
    deep_seek_api_key: Optional[str] = Field(alias="deepSeekApiKey")
    mistral_api_key: Optional[str] = Field(alias="mistralApiKey")
    perplexity_api_key: Optional[str] = Field(alias="perplexityApiKey")
    type_safe_api_key: Optional[str] = Field(alias="typeSafeApiKey")
    fal_api_key: Optional[str] = Field(alias="falApiKey")
    bedrock_model_config: Optional[Dict[str, Any]] = Field(
        alias="bedrockModelConfig",
    )
    vertex_ai_model_config: Optional[Dict[str, Any]] = Field(
        alias="vertexAiModelConfig",
    )
    azure_model_config: Optional[Dict[str, Any]] = Field(
        alias="azureModelConfig",
    )
    port_key_config: Optional[Dict[str, Any]] = Field(alias="portKeyConfig")
    open_router_config: Optional[Dict[str, Any]] = Field(
        alias="openRouterConfig",
    )
    true_foundry_config: Optional[Dict[str, Any]] = Field(
        alias="trueFoundryConfig",
    )
    lite_llm_config: Optional[Dict[str, Any]] = Field(alias="liteLlmConfig")
    hugging_face_config: Optional[Dict[str, Any]] = Field(
        alias="huggingFaceConfig",
    )
    organization_id: Optional[str] = Field(alias="organizationId")


class PendingRotationApiKey(ConfidentBaseModel):
    id: int
    name: Optional[str]
    valid: bool
    created_at: str
    expires_at: Optional[str] = Field(alias="expiresAt")
    value: str
    shadow_value: str = Field(alias="shadowValue")
    rotates_at: str = Field(alias="rotatesAt")
    last_used: Optional[str] = Field(alias="lastUsed")


class Permission(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]


class PermissionList(ConfidentBaseModel):
    permissions: List[Permission]


class PolicyPermission(ConfidentBaseModel):
    id: str
    name: str


class Policy(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]
    permissions: List[PolicyPermission]


class PolicyList(ConfidentBaseModel):
    policies: List[Policy]


class PolicyRef(ConfidentBaseModel):
    id: str


class RolePolicy(ConfidentBaseModel):
    id: str
    name: str


class RoleRef(ConfidentBaseModel):
    id: str


class RotateApiKeyRequest(ConfidentBaseModel):
    grace_period_in_hours: Optional[int] = Field(
        default=None,
        alias="gracePeriodInHours",
    )
    expires_in_days: Optional[int] = Field(default=None, alias="expiresInDays")


class ToolCall(ConfidentBaseModel):
    name: str
    type: Optional[ToolCallType] = None
    description: Optional[str] = None
    input_parameters: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="inputParameters",
    )
    output: Optional[Any] = None
    reasoning: Optional[str] = None


class Span(ConfidentBaseModel):
    uuid: str
    trace_uuid: str = Field(alias="traceUuid")
    parent_uuid: Optional[str] = Field(alias="parentUuid")
    name: Optional[str]
    type: SpanType
    status: TraceSpanStatus
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    error: Optional[str]
    integration: Optional[str]
    provider: Optional[str]
    model: Optional[str]
    endpoint: Optional[str]
    cost: Optional[float]
    input_token_cost: Optional[float] = Field(alias="inputTokenCost")
    output_token_cost: Optional[float] = Field(alias="outputTokenCost")
    cost_per_input_token: Optional[float] = Field(alias="costPerInputToken")
    cost_per_output_token: Optional[float] = Field(alias="costPerOutputToken")
    input_token_count: Optional[int] = Field(alias="inputTokenCount")
    output_token_count: Optional[int] = Field(alias="outputTokenCount")
    prompt_alias: Optional[str] = Field(alias="promptAlias")
    prompt_version: Optional[str] = Field(alias="promptVersion")
    prompt_label: Optional[str] = Field(alias="promptLabel")
    prompt_commit_hash: Optional[str] = Field(alias="promptCommitHash")
    embedder: Optional[str]
    top_k: Optional[int] = Field(alias="topK")
    chunk_size: Optional[int] = Field(alias="chunkSize")
    description: Optional[str]
    agent_handoffs: Optional[List[str]] = Field(alias="agentHandoffs")
    available_tools: Optional[List[str]] = Field(alias="availableTools")
    metadata: Optional[Dict[str, Any]]
    metric_collection_name: Optional[str] = Field(alias="metricCollectionName")
    input: Optional[str]
    output: Optional[str]
    expected_output: Optional[str] = Field(alias="expectedOutput")
    retrieval_context: Optional[List[str]] = Field(alias="retrievalContext")
    context: Optional[List[str]]
    tools_called: Optional[List[ToolCall]] = Field(alias="toolsCalled")
    expected_tools: Optional[List[ToolCall]] = Field(alias="expectedTools")
    metrics_data: List[MetricData] = Field(alias="metricsData")
    annotations: List[AnnotationSummary]


class Trace(ConfidentBaseModel):
    uuid: str
    name: Optional[str]
    status: TraceSpanStatus
    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")
    latency: int
    cost: Optional[float]
    thread_id: Optional[str] = Field(alias="threadId")
    user_id: Optional[str] = Field(alias="userId")
    customer_id: Optional[str] = Field(alias="customerId")
    environment: str
    tags: Optional[List[str]]
    metadata: Optional[Dict[str, Any]]
    input: Optional[str]
    output: Optional[str]
    expected_output: Optional[str] = Field(alias="expectedOutput")
    retrieval_context: Optional[List[str]] = Field(alias="retrievalContext")
    context: Optional[List[str]]
    tools_called: Optional[List[ToolCall]] = Field(alias="toolsCalled")
    expected_tools: Optional[List[ToolCall]] = Field(alias="expectedTools")
    test_case_id: Optional[str] = Field(alias="testCaseId")
    metric_collection_name: Optional[str] = Field(alias="metricCollectionName")
    labels: Dict[str, Classification]
    spans: Optional[List[Span]] = None
    metrics_data: List[MetricData] = Field(alias="metricsData")
    annotations: List[AnnotationSummary]


class Turn(ConfidentBaseModel):
    id: Optional[str] = None
    role: TurnRole
    content: str
    user_id: Optional[str] = Field(default=None, alias="userId")
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )


class UpdateApiKeyRequest(ConfidentBaseModel):
    valid: bool


class UpdateMemberRoleRequest(ConfidentBaseModel):
    role_id: str = Field(alias="roleId")


class UpdateModelCredentialsRequest(ConfidentBaseModel):
    provider: ModelProvider
    api_key: Optional[str] = Field(default=None, alias="apiKey")
    model_config_: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="modelConfig",
    )


class WidgetScalarValue(ConfidentBaseModel):
    key: str
    name: str
    color: WidgetLineColor
    line_id: Optional[str] = Field(default=None, alias="lineId")
    value: Optional[float]


class WidgetBigNumberData(ConfidentBaseModel):
    kind: Literal["BIG_NUMBER"]
    unit: Optional[WidgetUnit]
    values: List[WidgetScalarValue]


class WidgetSeriesPoint(ConfidentBaseModel):
    x: str
    y: Optional[float]


class WidgetSeries(ConfidentBaseModel):
    key: str
    name: str
    color: WidgetLineColor
    line_id: Optional[str] = Field(default=None, alias="lineId")
    points: List[WidgetSeriesPoint]


class WidgetDimensionData(ConfidentBaseModel):
    kind: Literal["DIMENSION"]
    unit: Optional[WidgetUnit]
    series: List[WidgetSeries]


class WidgetTableColumn(ConfidentBaseModel):
    key: str
    label: str


class WidgetTableData(ConfidentBaseModel):
    kind: Literal["TABLE"]
    columns: List[WidgetTableColumn]
    rows: List[Dict[str, Optional[Union[str, float]]]]


class WidgetTimeSeriesData(ConfidentBaseModel):
    kind: Literal["TIME_SERIES"]
    unit: Optional[WidgetUnit]
    series: List[WidgetSeries]


RotatedApiKey = Union[ImmediatelyRotatedApiKey, PendingRotationApiKey]


WidgetData = Union[
    WidgetBigNumberData,
    WidgetTimeSeriesData,
    WidgetDimensionData,
    WidgetTableData,
]
