# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: annotation-queues).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import Field

from confident_ai.common.types import (
    FilterSet,
    IngestionDataModel,
    MLLMImage,
    UserReference,
)
from confident_ai.types import ConfidentBaseModel


class AnnotationQueueType(Enum):
    TRACE = "TRACE"
    SPAN = "SPAN"
    THREAD = "THREAD"
    GOLDEN = "GOLDEN"
    TEST_RUN = "TEST_RUN"


class AssignmentStrategy(Enum):
    SINGLE_USER = "SINGLE_USER"
    ROUND_ROBIN = "ROUND_ROBIN"
    RANDOM = "RANDOM"


class QueueItemStatus(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    DRAFT = "DRAFT"
    DEFERRED = "DEFERRED"
    COMPLETED = "COMPLETED"


class AddSpanQueueItemsRequest(ConfidentBaseModel):
    span_uuids: List[str] = Field(alias="spanUuids")


class AddThreadQueueItemsRequest(ConfidentBaseModel):
    thread_ids: List[str] = Field(alias="threadIds")


class AddTraceQueueItemsRequest(ConfidentBaseModel):
    trace_uuids: List[str] = Field(alias="traceUuids")


class AddedQueueItems(ConfidentBaseModel):
    ids: List[str]


class QueueItemAnnotation(ConfidentBaseModel):
    field_type: Optional[Literal["THUMBS_RATING", "FIVE_STAR_RATING"]] = Field(
        default=None,
        alias="fieldType",
    )
    value: Union[bool, int]
    name: Optional[str] = None
    explanation: Optional[str] = None
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    expected_outcome: Optional[str] = Field(
        default=None,
        alias="expectedOutcome",
    )
    images_mapping: Optional[Dict[str, MLLMImage]] = Field(
        default=None,
        alias="imagesMapping",
    )


class QueueItemFormResponse(ConfidentBaseModel):
    label: str
    value: Optional[Any] = None


class AnnotateQueueItemRequest(ConfidentBaseModel):
    annotations: Optional[List[QueueItemAnnotation]] = None
    form_responses: Optional[List[QueueItemFormResponse]] = Field(
        default=None,
        alias="formResponses",
    )
    annotator_email: Optional[str] = Field(default=None, alias="annotatorEmail")
    flagged: Optional[bool] = None
    mark_as_completed: Optional[bool] = Field(
        default=None,
        alias="markAsCompleted",
    )


class AnnotateQueueItemResult(ConfidentBaseModel):
    annotation_ids: List[str] = Field(alias="annotationIds")
    form_response_ids: List[str] = Field(alias="formResponseIds")


class AssignmentBreakdownEntry(ConfidentBaseModel):
    assigned: int
    completed: int


class AnnotationQueue(ConfidentBaseModel):
    id: str
    name: str
    type: AnnotationQueueType
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")
    test_run_id: Optional[str] = Field(alias="testRunId")
    form_id: Optional[str] = Field(alias="formId")
    tags: List[str]
    total_items: int = Field(alias="totalItems")
    completed_items: int = Field(alias="completedItems")
    pending_items: int = Field(alias="pendingItems")
    completion_percentage: int = Field(alias="completionPercentage")
    assigned_items: int = Field(alias="assignedItems")
    assignment_breakdown: Dict[str, AssignmentBreakdownEntry] = Field(
        alias="assignmentBreakdown",
    )


class AnnotationQueueItem(ConfidentBaseModel):
    id: str
    trace_uuid: Optional[str] = Field(alias="traceUuid")
    span_uuid: Optional[str] = Field(alias="spanUuid")
    thread_id: Optional[str] = Field(alias="threadId")
    test_case_id: Optional[str] = Field(alias="testCaseId")
    added_at: str = Field(alias="addedAt")
    status: QueueItemStatus
    assigned_to_email: Optional[str] = Field(alias="assignedToEmail")


class AnnotationQueueItemList(ConfidentBaseModel):
    items: List[AnnotationQueueItem]
    total_annotation_queue_items: int = Field(alias="totalAnnotationQueueItems")
    page: int
    page_size: int = Field(alias="pageSize")


class AnnotationQueueSummary(ConfidentBaseModel):
    id: str
    name: str
    type: AnnotationQueueType
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")
    test_run_id: Optional[str] = Field(alias="testRunId")
    form_id: Optional[str] = Field(alias="formId")
    tags: List[str]
    total_items: int = Field(alias="totalItems")
    completed_items: int = Field(alias="completedItems")
    pending_items: int = Field(alias="pendingItems")
    completion_percentage: int = Field(alias="completionPercentage")


class AnnotationQueueList(ConfidentBaseModel):
    annotation_queues: List[AnnotationQueueSummary] = Field(
        alias="annotationQueues",
    )
    total_annotation_queues: int = Field(alias="totalAnnotationQueues")
    page: int
    page_size: int = Field(alias="pageSize")


class AnnotationQueueRef(ConfidentBaseModel):
    id: str


class BatchAnnotateFailure(ConfidentBaseModel):
    queue_item_id: str = Field(alias="queueItemId")
    success: Literal[False]
    error: str


class BatchAnnotateItem(ConfidentBaseModel):
    queue_item_id: str = Field(alias="queueItemId")
    annotations: Optional[List[QueueItemAnnotation]] = None
    form_responses: Optional[List[QueueItemFormResponse]] = Field(
        default=None,
        alias="formResponses",
    )
    annotator_email: Optional[str] = Field(default=None, alias="annotatorEmail")
    flagged: Optional[bool] = None
    mark_as_completed: Optional[bool] = Field(
        default=None,
        alias="markAsCompleted",
    )


class BatchAnnotateRequest(ConfidentBaseModel):
    annotator_email: Optional[str] = Field(default=None, alias="annotatorEmail")
    mark_as_completed: Optional[bool] = Field(
        default=None,
        alias="markAsCompleted",
    )
    items: List[BatchAnnotateItem]


class BatchAnnotateSuccess(ConfidentBaseModel):
    queue_item_id: str = Field(alias="queueItemId")
    success: Literal[True]
    annotation_ids: List[str] = Field(alias="annotationIds")
    form_response_ids: List[str] = Field(alias="formResponseIds")


class BatchAnnotateResult(ConfidentBaseModel):
    results: List[Union[BatchAnnotateSuccess, BatchAnnotateFailure]]


class CreateAnnotationQueueRequest(ConfidentBaseModel):
    name: str
    type: AnnotationQueueType
    form_id: Optional[str] = Field(default=None, alias="formId")
    tags: Optional[List[str]] = None


class CreateQueueIngestionTaskRequest(ConfidentBaseModel):
    name: str
    data_model: IngestionDataModel = Field(alias="dataModel")
    description: Optional[str] = None
    enabled: Optional[bool] = None
    sample_rate: Optional[float] = Field(default=None, alias="sampleRate")
    filters: Optional[FilterSet] = None
    max_items: Optional[int] = Field(default=None, alias="maxItems")
    assignment_strategy: Optional[AssignmentStrategy] = Field(
        default=None,
        alias="assignmentStrategy",
    )
    reviewer_emails: Optional[List[str]] = Field(
        default=None,
        alias="reviewerEmails",
    )


class QueueIngestionTask(ConfidentBaseModel):
    id: str
    annotation_queue_id: Optional[str] = Field(alias="annotationQueueId")
    name: str
    description: Optional[str]
    enabled: bool
    sample_rate: float = Field(alias="sampleRate")
    data_model: IngestionDataModel = Field(alias="dataModel")
    filters: Optional[FilterSet]
    max_items: Optional[int] = Field(alias="maxItems")
    assignment_strategy: AssignmentStrategy = Field(alias="assignmentStrategy")
    reviewers: List[UserReference]
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")


class QueueIngestionTaskSummary(ConfidentBaseModel):
    id: str
    name: str
    enabled: bool
    data_model: IngestionDataModel = Field(alias="dataModel")


class QueueIngestionTaskList(ConfidentBaseModel):
    queue_ingestion_tasks: List[QueueIngestionTaskSummary] = Field(
        alias="queueIngestionTasks",
    )


class QueueIngestionTaskRef(ConfidentBaseModel):
    id: str


class UpdateAnnotationQueueRequest(ConfidentBaseModel):
    name: Optional[str] = None
    form_id: Optional[str] = Field(default=None, alias="formId")
    tags: Optional[List[str]] = None


class UpdateQueueIngestionTaskRequest(ConfidentBaseModel):
    name: Optional[str] = None
    data_model: Optional[IngestionDataModel] = Field(
        default=None,
        alias="dataModel",
    )
    new_annotation_queue_id: Optional[str] = Field(
        default=None,
        alias="newAnnotationQueueId",
    )
    description: Optional[str] = None
    enabled: Optional[bool] = None
    sample_rate: Optional[float] = Field(default=None, alias="sampleRate")
    filters: Optional[FilterSet] = None
    max_items: Optional[int] = Field(default=None, alias="maxItems")
    assignment_strategy: Optional[AssignmentStrategy] = Field(
        default=None,
        alias="assignmentStrategy",
    )
    reviewer_emails: Optional[List[str]] = Field(
        default=None,
        alias="reviewerEmails",
    )


AddQueueItemsRequest = Union[
    AddTraceQueueItemsRequest,
    AddSpanQueueItemsRequest,
    AddThreadQueueItemsRequest,
]
