// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: annotation-queues).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { ItemsOperations } from "../items/operations";
import { FilterSet, IngestionDataModel } from "../../common/types";
import {
  AssignmentStrategy,
  QueueIngestionTask,
  QueueIngestionTaskList,
  QueueIngestionTaskRef,
} from "../types";

export class QueueIngestionTasksOperations extends ItemsOperations {
  /**
   * List Queue Ingestion Tasks
   *
   * Lists the ingestion tasks filling an annotation queue, newest first. Each
   * task is returned as a summary; retrieve a task by id for its filters and
   * reviewers.
   *
   * @param annotationQueueId The id of the annotation queue.
   * @param dataModel Returns only tasks harvesting this kind of production
   *   item.
   */
  async listQueueIngestionTasks(
    annotationQueueId: string,
    dataModel?: IngestionDataModel,
  ): Promise<QueueIngestionTaskList> {
    return this.api.sendRequest<QueueIngestionTaskList>(
      HttpMethods.GET,
      Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
      { urlParams: { annotationQueueId }, params: { dataModel } },
    );
  }

  /**
   * Create Queue Ingestion Task
   *
   * Creates a rule that keeps an annotation queue filled from your production
   * data, and returns its id. A task only harvests once `enabled` is `true`.
   *
   * @param annotationQueueId The id of the annotation queue.
   * @param name The name of the task.
   * @param description A note about what the task harvests. Send `null` to
   *   clear it.
   * @param enabled Whether the task runs. Disabling it stops new items
   *   arriving; items already queued are kept. Defaults to `false` on create;
   *   omit it on an update to leave it unchanged.
   * @param sampleRate The fraction of matching items to queue, between 0 and 1.
   *   On create it defaults to 1, all of them; omit it on an update to leave it
   *   unchanged.
   * @param maxItems The maximum number of items this task will ever queue. Send
   *   `null` to remove the cap.
   * @param reviewerEmails The project members harvested items are assigned to,
   *   following `assignmentStrategy`.
   */
  async createQueueIngestionTask(
    annotationQueueId: string,
    name: string,
    dataModel: IngestionDataModel,
    options: {
      description?: string | null;
      enabled?: boolean;
      sampleRate?: number;
      filters?: FilterSet;
      maxItems?: number | null;
      assignmentStrategy?: AssignmentStrategy;
      reviewerEmails?: string[];
    } = {},
  ): Promise<QueueIngestionTaskRef> {
    const {
      description,
      enabled,
      sampleRate,
      filters,
      maxItems,
      assignmentStrategy,
      reviewerEmails,
    } = options;
    return this.api.sendRequest<QueueIngestionTaskRef>(
      HttpMethods.POST,
      Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
      {
        body: {
          name,
          dataModel,
          description,
          enabled,
          sampleRate,
          filters,
          maxItems,
          assignmentStrategy,
          reviewerEmails,
        },
        urlParams: { annotationQueueId },
      },
    );
  }

  /**
   * Get Queue Ingestion Task
   *
   * Retrieves one of the queue's ingestion tasks by id, with its full
   * configuration.
   *
   * @param annotationQueueId The id of the annotation queue the task fills.
   * @param queueIngestionTaskId The id of the queue ingestion task.
   */
  async getQueueIngestionTask(
    annotationQueueId: string,
    queueIngestionTaskId: string,
  ): Promise<QueueIngestionTask> {
    return this.api.sendRequest<QueueIngestionTask>(
      HttpMethods.GET,
      Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
      { urlParams: { annotationQueueId, queueIngestionTaskId } },
    );
  }

  /**
   * Update Queue Ingestion Task
   *
   * Updates an ingestion task and returns it. A field you omit keeps its stored
   * value; items already queued by the task are kept whatever you change.
   *
   * @param annotationQueueId The id of the annotation queue the task fills.
   * @param queueIngestionTaskId The id of the queue ingestion task.
   * @param name The name of the task.
   * @param newAnnotationQueueId Moves the task to another queue, which must
   *   hold the same data model. Later items are queued there; items already
   *   queued stay where they are. Send `null` to detach the task, which only a
   *   recurring task may do — it then creates a queue of its own each period.
   * @param description A note about what the task harvests. Send `null` to
   *   clear it.
   * @param enabled Whether the task runs. Disabling it stops new items
   *   arriving; items already queued are kept. Defaults to `false` on create;
   *   omit it on an update to leave it unchanged.
   * @param sampleRate The fraction of matching items to queue, between 0 and 1.
   *   On create it defaults to 1, all of them; omit it on an update to leave it
   *   unchanged.
   * @param maxItems The maximum number of items this task will ever queue. Send
   *   `null` to remove the cap.
   * @param reviewerEmails The project members harvested items are assigned to,
   *   following `assignmentStrategy`.
   */
  async updateQueueIngestionTask(
    annotationQueueId: string,
    queueIngestionTaskId: string,
    options: {
      name?: string;
      dataModel?: IngestionDataModel;
      newAnnotationQueueId?: string | null;
      description?: string | null;
      enabled?: boolean;
      sampleRate?: number;
      filters?: FilterSet;
      maxItems?: number | null;
      assignmentStrategy?: AssignmentStrategy;
      reviewerEmails?: string[];
    } = {},
  ): Promise<QueueIngestionTask> {
    const {
      name,
      dataModel,
      newAnnotationQueueId,
      description,
      enabled,
      sampleRate,
      filters,
      maxItems,
      assignmentStrategy,
      reviewerEmails,
    } = options;
    return this.api.sendRequest<QueueIngestionTask>(
      HttpMethods.PUT,
      Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
      {
        body: {
          name,
          dataModel,
          newAnnotationQueueId,
          description,
          enabled,
          sampleRate,
          filters,
          maxItems,
          assignmentStrategy,
          reviewerEmails,
        },
        urlParams: { annotationQueueId, queueIngestionTaskId },
      },
    );
  }

  /**
   * Delete Queue Ingestion Task
   *
   * Permanently deletes an ingestion task, so it stops filling the queue. Items
   * it already queued are kept.
   *
   * @param annotationQueueId The id of the annotation queue the task fills.
   * @param queueIngestionTaskId The id of the queue ingestion task.
   */
  async deleteQueueIngestionTask(
    annotationQueueId: string,
    queueIngestionTaskId: string,
  ): Promise<QueueIngestionTaskRef> {
    return this.api.sendRequest<QueueIngestionTaskRef>(
      HttpMethods.DELETE,
      Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
      { urlParams: { annotationQueueId, queueIngestionTaskId } },
    );
  }
}
