// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: traces).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import { ToolCall, Trace, TraceSpanStatus } from "../common/types";
import {
  CustomerRequest,
  MetricDataConfig,
  SpanRequest,
  ThreadRequest,
  TraceAttachment,
  TraceList,
  TraceRef,
  TraceSortBy,
  UserRequest,
} from "./types";

export class TracesClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Traces
   *
   * Lists the traces in your Confident AI project one page at a time, newest
   * first by default, as summary rows. Retrieve a trace by uuid for its full
   * detail.
   *
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   * @param cursor This is used for pagination, and should be set to the
   *   `nextCursor` value returned in the previous response to get the next page
   *   of results.
   * @param start This filters for results created at or after the specified
   *   start datetime, in ISO 8601 format. Defaults to 60 days ago.
   * @param end This filters for results created before the specified end
   *   datetime, in ISO 8601 format. Defaults to the current time.
   * @param ascending This determines if the field specified in `sortBy` should
   *   be in ascending order. Defaults to `false`, which returns the newest
   *   results first.
   * @param sortBy This determines the field to sort by. Defaults to
   *   `createdAt`.
   * @param environment This filters the traces by the environment where the
   *   trace was created, and returns traces from all environments if not
   *   specified.
   * @param metadata Filter traces by metadata key-value pairs using bracket
   *   notation, for example `metadata[client]=acme-corp`. Every pair must
   *   match.
   */
  async list(
    options: {
      pageSize?: number;
      cursor?: string;
      start?: string;
      end?: string;
      ascending?: "true" | "false";
      sortBy?: TraceSortBy;
      environment?: string;
      metadata?: Record<string, string>;
    } = {},
  ): Promise<TraceList> {
    const {
      pageSize,
      cursor,
      start,
      end,
      ascending,
      sortBy,
      environment,
      metadata,
    } = options;
    return this.api.sendRequest<TraceList>(
      HttpMethods.GET,
      Endpoints.TRACES_ENDPOINT,
      {
        params: {
          pageSize,
          cursor,
          start,
          end,
          ascending,
          sortBy,
          environment,
          metadata,
        },
      },
    );
  }

  /**
   * Create Trace
   *
   * Creates a trace in your Confident AI project, along with the spans it
   * contains, and returns its uuid. A `uuid` that is not a UUID is hashed into
   * one, so the returned value is what every later lookup uses.
   *
   * @param uuid The unique identifier of the trace, generated by your
   *   application. Values that are not UUIDs are hashed into one, and the
   *   hashed uuid is what the response and every later lookup use.
   * @param startTime This is the time the trace started, as an ISO 8601
   *   datetime.
   * @param endTime This is the time the trace ended, as an ISO 8601 datetime.
   * @param name This is the name of the trace.
   * @param input This is the input to the trace, as a string or any JSON value.
   * @param output This is the output of the trace, as a string or any JSON
   *   value.
   * @param environment This is the environment where your trace was posted,
   *   which helps with separating and debugging traces from different
   *   environments on the Confident AI platform. Any name up to 64 characters
   *   is accepted, for example production, staging or eu-prod.
   * @param metadata This is any additional metadata associated with the trace.
   * @param tags This is any tags associated with the trace, which helps with
   *   grouping traces and filtering them on the Confident AI platform.
   * @param threadId This is the unique identifier of the thread associated with
   *   the trace, which groups traces in the same thread into a conversation.
   * @param userId This is the unique identifier for your end user for the
   *   trace.
   * @param customerId This is the unique identifier of the customer the trace
   *   belongs to — the account, tenant or organization your end user belongs
   *   to.
   * @param metricCollection This is the metric collection you wish to use to
   *   evaluate the trace.
   * @param testRunId This is the unique identifier of the test run to associate
   *   the trace with. When set, the trace becomes one test case in that test
   *   run and `metricCollection` is required. It cannot be combined with
   *   `testCaseId`.
   * @param testCaseId The id of an existing test case to attach the trace to,
   *   when the trace was produced while evaluating that test case.
   * @param turnId The id of the conversational test case turn to attach the
   *   trace to, when the trace was produced while evaluating that turn.
   * @param retrievalContext This is the retrieval context of your trace, which
   *   is to be used for evaluation.
   * @param context This is the ideal retrieval context of your trace, which is
   *   to be used for evaluation.
   * @param expectedOutput This is the expected output of your trace, which is
   *   the ideal actual output and to be used for evaluation.
   * @param toolsCalled This is the tools called by your trace, which is to be
   *   used for evaluation.
   * @param expectedTools This is the expected tools to be called by the trace,
   *   which is to be used for evaluation.
   * @param spans This is the list of spans in the trace. Each span's `type`
   *   decides which fields it accepts.
   * @param metricsData Metric results you already computed for this trace,
   *   recorded as-is instead of being evaluated by Confident AI.
   * @param attachments Map of attachment ids to payloads for all
   *   `[DEEPEVAL:IMAGE:…]` and `[DEEPEVAL:PDF:…]` markers in this trace. Define
   *   attachments at the trace level with the same ids for the same instances.
   */
  async create(
    uuid: string,
    startTime: string,
    endTime: string,
    options: {
      name?: string;
      input?: unknown;
      output?: unknown;
      status?: TraceSpanStatus;
      environment?: string;
      metadata?: Record<string, unknown>;
      tags?: string[];
      threadId?: string;
      thread?: ThreadRequest;
      userId?: string;
      user?: UserRequest;
      customerId?: string;
      customer?: CustomerRequest;
      metricCollection?: string;
      testRunId?: string;
      testCaseId?: string;
      turnId?: string;
      retrievalContext?: string[];
      context?: string[];
      expectedOutput?: string;
      toolsCalled?: ToolCall[];
      expectedTools?: ToolCall[];
      spans?: SpanRequest[];
      metricsData?: MetricDataConfig[];
      attachments?: Record<string, TraceAttachment>;
    } = {},
  ): Promise<TraceRef> {
    const {
      name,
      input,
      output,
      status,
      environment,
      metadata,
      tags,
      threadId,
      thread,
      userId,
      user,
      customerId,
      customer,
      metricCollection,
      testRunId,
      testCaseId,
      turnId,
      retrievalContext,
      context,
      expectedOutput,
      toolsCalled,
      expectedTools,
      spans,
      metricsData,
      attachments,
    } = options;
    return this.api.sendRequest<TraceRef>(
      HttpMethods.POST,
      Endpoints.TRACES_ENDPOINT,
      {
        body: {
          uuid,
          startTime,
          endTime,
          name,
          input,
          output,
          status,
          environment,
          metadata,
          tags,
          threadId,
          thread,
          userId,
          user,
          customerId,
          customer,
          metricCollection,
          testRunId,
          testCaseId,
          turnId,
          retrievalContext,
          context,
          expectedOutput,
          toolsCalled,
          expectedTools,
          spans,
          metricsData,
          attachments,
        },
      },
    );
  }

  /**
   * Get Trace
   *
   * Retrieves a trace by uuid from your Confident AI project, with its spans,
   * full input and output, evaluation fields, classifier labels, results and
   * annotations.
   *
   * @param traceUuid The unique identifier of the trace.
   */
  async get(traceUuid: string): Promise<Trace> {
    return this.api.sendRequest<Trace>(
      HttpMethods.GET,
      Endpoints.TRACE_ENDPOINT,
      { urlParams: { traceUuid } },
    );
  }
}
