// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: traces).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  EvaluationErrorType,
  ToolCall,
  TraceSpanStatus,
} from "../common/types";

export enum TraceSortBy {
  CREATEDAT = "createdAt",
  ENDEDAT = "endedAt",
}

export interface MetricDataConfig {
  name: string;
  score?: number | null;
  success?: boolean | null;
  threshold?: number | null;
  strictMode?: boolean;
  flaky?: boolean;
  reason?: string | null;
  evaluationModel?: string | null;
  evaluationCost?: number | null;
  error?: string | null;
  errorType?: EvaluationErrorType | null;
  verboseLogs?: string | null;
}

export interface AgentSpanRequest {
  type: "AGENT";
  uuid: string;
  name: string;
  input?: unknown;
  output?: unknown;
  error?: string;
  status?: TraceSpanStatus;
  startTime: string;
  endTime: string;
  parentUuid?: string;
  metadata?: Record<string, unknown>;
  metricCollection?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  integration?: string;
  metricsData?: MetricDataConfig[];
  availableTools: string[];
  agentHandoffs: string[];
}

export interface BaseSpanRequest {
  type?: "SPAN";
  uuid: string;
  name: string;
  input?: unknown;
  output?: unknown;
  error?: string;
  status?: TraceSpanStatus;
  startTime: string;
  endTime: string;
  parentUuid?: string;
  metadata?: Record<string, unknown>;
  metricCollection?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  integration?: string;
  metricsData?: MetricDataConfig[];
}

export interface ThreadRequest {
  id?: string;
  metadata?: Record<string, unknown> | null;
  tags?: string[] | null;
}

export interface UserRequest {
  id?: string;
  name?: string | null;
}

export interface CustomerRequest {
  id?: string;
  name?: string | null;
}

export interface LlmSpanRequest {
  type: "LLM";
  uuid: string;
  name: string;
  input?: unknown;
  output?: unknown;
  error?: string;
  status?: TraceSpanStatus;
  startTime: string;
  endTime: string;
  parentUuid?: string;
  metadata?: Record<string, unknown>;
  metricCollection?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  integration?: string;
  metricsData?: MetricDataConfig[];
  model?: string;
  provider?: string;
  endpoint?: string;
  costPerInputToken?: number;
  costPerOutputToken?: number;
  inputTokenCount?: number;
  outputTokenCount?: number;
  promptAlias?: string;
  promptVersion?: string;
  promptLabel?: string;
  promptCommitHash?: string;
}

export interface RetrieverSpanRequest {
  type: "RETRIEVER";
  uuid: string;
  name: string;
  input?: unknown;
  output?: unknown;
  error?: string;
  status?: TraceSpanStatus;
  startTime: string;
  endTime: string;
  parentUuid?: string;
  metadata?: Record<string, unknown>;
  metricCollection?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  integration?: string;
  metricsData?: MetricDataConfig[];
  embedder: string;
  topK?: number;
  chunkSize?: number;
}

export interface ToolSpanRequest {
  type: "TOOL";
  uuid: string;
  name: string;
  input?: unknown;
  output?: unknown;
  error?: string;
  status?: TraceSpanStatus;
  startTime: string;
  endTime: string;
  parentUuid?: string;
  metadata?: Record<string, unknown>;
  metricCollection?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  integration?: string;
  metricsData?: MetricDataConfig[];
  description?: string;
}

export type SpanRequest =
  | BaseSpanRequest
  | LlmSpanRequest
  | RetrieverSpanRequest
  | ToolSpanRequest
  | AgentSpanRequest;

export interface TraceAttachment {
  url?: string;
  dataBase64?: string;
  mimeType?: string;
}

export interface CreateTraceRequest {
  uuid: string;
  name?: string;
  input?: unknown;
  output?: unknown;
  startTime: string;
  endTime: string;
  status?: TraceSpanStatus;
  environment?: string;
  metadata?: Record<string, unknown>;
  tags?: string[];
  threadId?: string;
  thread?: ThreadRequest;
  userId?: string;
  user?: UserRequest;
  customerId?: string;
  customer?: CustomerRequest;
  metricCollection?: string;
  testRunId?: string;
  testCaseId?: string;
  turnId?: string;
  retrievalContext?: string[];
  context?: string[];
  expectedOutput?: string;
  toolsCalled?: ToolCall[];
  expectedTools?: ToolCall[];
  spans?: SpanRequest[];
  metricsData?: MetricDataConfig[];
  attachments?: Record<string, TraceAttachment>;
}

export interface TraceSummary {
  uuid: string;
  name: string | null;
  status: TraceSpanStatus;
  startTime: string;
  endTime: string;
  latency: number;
  cost: number | null;
  threadId: string | null;
  userId: string | null;
  customerId: string | null;
  environment: string;
  tags: string[] | null;
  metadata: Record<string, unknown> | null;
  inputPreview: string | null;
  outputPreview: string | null;
}

export interface TraceList {
  traces: TraceSummary[];
  totalTraces?: number;
  nextCursor: string | null;
}

export interface TraceRef {
  uuid: string;
}
