// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: export-schedules).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import {
  FilterSet,
  ScheduleIntervalUnit,
  ScheduleRecurrenceType,
} from "../common/types";
import {
  AnnotationSelectionType,
  ExportSchedule,
  ExportScheduleList,
  ExportScheduleRef,
  SchedulableExportType,
} from "./types";

export class ExportSchedulesClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Export Schedules
   *
   * Lists the export schedules in your Confident AI project one page at a time,
   * newest first. Narrow the page with `exportType` or `enabled`; retrieve one
   * by id to see its cadence, filters and destination.
   *
   * @param enabled Return only the schedules that are currently running, or
   *   only those that are paused. Omit it for both.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async list(
    options: {
      exportType?: SchedulableExportType;
      enabled?: "true" | "false";
      page?: number;
      pageSize?: number;
    } = {},
  ): Promise<ExportScheduleList> {
    const { exportType, enabled, page, pageSize } = options;
    return this.api.sendRequest<ExportScheduleList>(
      HttpMethods.GET,
      Endpoints.EXPORT_SCHEDULES_ENDPOINT,
      { params: { exportType, enabled, page, pageSize } },
    );
  }

  /**
   * Create Export Schedule
   *
   * Creates an export schedule in your Confident AI project and returns its id.
   * Each run exports the window since the previous run and delivers it to the
   * export destination you name, so a schedule starts producing files as soon
   * as it is enabled.
   *
   * @param name The name of the schedule.
   * @param repeatEvery How many `repeatUnit`s apart the runs are, for an
   *   `INTERVAL` schedule. Send `null` to clear it.
   * @param repeatUnit The unit `repeatEvery` counts, for an `INTERVAL`
   *   schedule. Send `null` to clear it.
   * @param startAt When the schedule first runs, as an ISO 8601 datetime. Send
   *   `null` to start it immediately.
   * @param maxRuns How many times the schedule runs before it stops. Send
   *   `null` to let it run indefinitely.
   * @param endAt When the schedule stops running, as an ISO 8601 datetime. Send
   *   `null` to leave it open-ended.
   * @param description What the schedule exports. Send `null` to leave it
   *   unset.
   * @param environment The environment each run exports data from. Omit it, or
   *   send `null`, to export data from every environment. Ignored for
   *   `TEST_RUNS` exports, which have no environment.
   * @param annotationSelectionType The annotation source for each `ANNOTATIONS`
   *   export run. Omit it, or send `null`, to export annotations from every
   *   source. Ignored for other export types.
   * @param destinationId The id of the export destination each run delivers its
   *   file to. A scheduled run has no recipient of its own, so a schedule
   *   created without a destination produces files that go nowhere.
   * @param enabled Whether the schedule starts running as soon as it is
   *   created. Defaults to `true`.
   */
  async create(
    name: string,
    exportType: SchedulableExportType,
    options: {
      recurrence?: ScheduleRecurrenceType;
      repeatEvery?: number | null;
      repeatUnit?: ScheduleIntervalUnit | null;
      startAt?: string | null;
      maxRuns?: number | null;
      endAt?: string | null;
      description?: string | null;
      filters?: FilterSet;
      environment?: string | null;
      annotationSelectionType?: AnnotationSelectionType | null;
      destinationId?: string | null;
      enabled?: boolean;
    } = {},
  ): Promise<ExportScheduleRef> {
    const {
      recurrence,
      repeatEvery,
      repeatUnit,
      startAt,
      maxRuns,
      endAt,
      description,
      filters,
      environment,
      annotationSelectionType,
      destinationId,
      enabled,
    } = options;
    return this.api.sendRequest<ExportScheduleRef>(
      HttpMethods.POST,
      Endpoints.EXPORT_SCHEDULES_ENDPOINT,
      {
        body: {
          name,
          exportType,
          recurrence,
          repeatEvery,
          repeatUnit,
          startAt,
          maxRuns,
          endAt,
          description,
          filters,
          environment,
          annotationSelectionType,
          destinationId,
          enabled,
        },
      },
    );
  }

  /**
   * Get Export Schedule
   *
   * Retrieves an export schedule by id, with the filters and destination each
   * of its runs uses.
   *
   * @param exportScheduleId The id of the export schedule.
   */
  async get(exportScheduleId: string): Promise<ExportSchedule> {
    return this.api.sendRequest<ExportSchedule>(
      HttpMethods.GET,
      Endpoints.EXPORT_SCHEDULE_ENDPOINT,
      { urlParams: { exportScheduleId } },
    );
  }

  /**
   * Update Export Schedule
   *
   * Changes an export schedule and returns it. Changing the cadence or pausing
   * the schedule re-registers its next run; `exportType` is fixed at creation,
   * because changing it would re-target every future run.
   *
   * @param exportScheduleId The id of the export schedule.
   * @param repeatEvery How many `repeatUnit`s apart the runs are, for an
   *   `INTERVAL` schedule. Send `null` to clear it.
   * @param repeatUnit The unit `repeatEvery` counts, for an `INTERVAL`
   *   schedule. Send `null` to clear it.
   * @param startAt When the schedule first runs, as an ISO 8601 datetime. Send
   *   `null` to start it immediately.
   * @param maxRuns How many times the schedule runs before it stops. Send
   *   `null` to let it run indefinitely.
   * @param endAt When the schedule stops running, as an ISO 8601 datetime. Send
   *   `null` to leave it open-ended.
   * @param name The name of the schedule.
   * @param description What the schedule exports. Send `null` to clear it.
   * @param environment The environment each run exports data from. Send `null`
   *   to export data from every environment. Ignored for `TEST_RUNS` exports,
   *   which have no environment.
   * @param annotationSelectionType The annotation source for each `ANNOTATIONS`
   *   export run. Send `null` to export annotations from every source. Ignored
   *   for other export types.
   * @param destinationId The id of the export destination each run delivers its
   *   file to. Send `null` to leave the schedule without one.
   * @param enabled Whether the schedule runs. Send `false` to pause it without
   *   deleting it.
   */
  async update(
    exportScheduleId: string,
    options: {
      recurrence?: ScheduleRecurrenceType;
      repeatEvery?: number | null;
      repeatUnit?: ScheduleIntervalUnit | null;
      startAt?: string | null;
      maxRuns?: number | null;
      endAt?: string | null;
      name?: string;
      description?: string | null;
      filters?: FilterSet;
      environment?: string | null;
      annotationSelectionType?: AnnotationSelectionType | null;
      destinationId?: string | null;
      enabled?: boolean;
    } = {},
  ): Promise<ExportSchedule> {
    const {
      recurrence,
      repeatEvery,
      repeatUnit,
      startAt,
      maxRuns,
      endAt,
      name,
      description,
      filters,
      environment,
      annotationSelectionType,
      destinationId,
      enabled,
    } = options;
    return this.api.sendRequest<ExportSchedule>(
      HttpMethods.PUT,
      Endpoints.EXPORT_SCHEDULE_ENDPOINT,
      {
        body: {
          recurrence,
          repeatEvery,
          repeatUnit,
          startAt,
          maxRuns,
          endAt,
          name,
          description,
          filters,
          environment,
          annotationSelectionType,
          destinationId,
          enabled,
        },
        urlParams: { exportScheduleId },
      },
    );
  }

  /**
   * Delete Export Schedule
   *
   * Permanently deletes an export schedule and unregisters its next run. Files
   * its earlier runs already delivered are kept.
   *
   * @param exportScheduleId The id of the export schedule.
   */
  async delete(exportScheduleId: string): Promise<ExportScheduleRef> {
    return this.api.sendRequest<ExportScheduleRef>(
      HttpMethods.DELETE,
      Endpoints.EXPORT_SCHEDULE_ENDPOINT,
      { urlParams: { exportScheduleId } },
    );
  }
}
