// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: export-schedules).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  FilterSet,
  ScheduleIntervalUnit,
  ScheduleRecurrenceType,
} from "../common/types";

export enum AnnotationSelectionType {
  SPANS = "Spans",
  THREADS = "Threads",
  TRACES = "Traces",
}

export enum SchedulableExportType {
  TRACES = "TRACES",
  TRACES_WITH_SPANS = "TRACES_WITH_SPANS",
  CONVERSATIONS = "CONVERSATIONS",
  CONVERSATION_METRICS = "CONVERSATION_METRICS",
  ANNOTATIONS = "ANNOTATIONS",
  TEST_RUNS = "TEST_RUNS",
  AUDIT_LOGS = "AUDIT_LOGS",
}

export interface CreateExportScheduleRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  name: string;
  description?: string | null;
  exportType: SchedulableExportType;
  filters?: FilterSet;
  environment?: string | null;
  annotationSelectionType?: AnnotationSelectionType | null;
  destinationId?: string | null;
  enabled?: boolean;
}

export interface ExportScheduleSettings {
  recurrence: ScheduleRecurrenceType;
  repeatEvery: number | null;
  repeatUnit: ScheduleIntervalUnit | null;
  startAt: string | null;
  endAt: string | null;
  maxRuns: number | null;
  runCount: number;
  lastRunAt: string | null;
  enabled: boolean;
}

export interface ExportSchedule {
  id: string;
  name: string;
  description: string | null;
  exportType: SchedulableExportType;
  filters: FilterSet;
  environment: string | null;
  annotationSelectionType: AnnotationSelectionType | null;
  destinationId: string | null;
  scheduleSettings: ExportScheduleSettings | null;
  createdAt: string;
  updatedAt: string;
}

export interface ExportScheduleSummary {
  id: string;
  name: string;
  exportType: SchedulableExportType;
  enabled: boolean;
}

export interface ExportScheduleList {
  exportSchedules: ExportScheduleSummary[];
  totalExportSchedules: number;
  page: number;
  pageSize: number;
}

export interface ExportScheduleRef {
  id: string;
}

export interface UpdateExportScheduleRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  name?: string;
  description?: string | null;
  filters?: FilterSet;
  environment?: string | null;
  annotationSelectionType?: AnnotationSelectionType | null;
  destinationId?: string | null;
  enabled?: boolean;
}
