# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: threads).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Literal, Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.endpoints import Endpoints
from confident_ai.threads.types import Thread, ThreadList, ThreadSortBy


class ThreadsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[ThreadSortBy] = None,
        environment: Optional[str] = None
    ) -> ThreadList:
        """List Threads

        Lists the threads in your Confident AI project one page at a time, most
        recently active first by default. Each thread is returned as a summary;
        retrieve a thread by id for its traces, evaluation results and
        annotations.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `lastActivity`.
            environment: This filters the threads by the environment where their
                traces were created, and returns threads from all environments
                if not specified.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.THREADS_ENDPOINT,
            response_schema=ThreadList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
            },
        )

    async def a_list(
        self,
        *,
        page_size: Optional[int] = None,
        cursor: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        sort_by: Optional[ThreadSortBy] = None,
        environment: Optional[str] = None
    ) -> ThreadList:
        """List Threads

        Lists the threads in your Confident AI project one page at a time, most
        recently active first by default. Each thread is returned as a summary;
        retrieve a thread by id for its traces, evaluation results and
        annotations.

        Args:
            page_size: The number of results per page, at most 100. Defaults to
                25.
            cursor: This is used for pagination, and should be set to the
                `nextCursor` value returned in the previous response to get the
                next page of results.
            start: This filters for results created at or after the specified
                start datetime, in ISO 8601 format. Defaults to 60 days ago.
            end: This filters for results created before the specified end
                datetime, in ISO 8601 format. Defaults to the current time.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest results first.
            sort_by: This determines the field to sort by. Defaults to
                `lastActivity`.
            environment: This filters the threads by the environment where their
                traces were created, and returns threads from all environments
                if not specified.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.THREADS_ENDPOINT,
            response_schema=ThreadList,
            query={
                "pageSize": page_size,
                "cursor": cursor,
                "start": start,
                "end": end,
                "ascending": ascending,
                "sortBy": sort_by,
                "environment": environment,
            },
        )

    def get(self, thread_id: str) -> Thread:
        """Get Thread

        Retrieves a thread by id from your Confident AI project, with its
        evaluation results, annotations and the first 100 traces of the
        conversation, oldest first.

        Args:
            thread_id: The id of the thread, as you supplied it when creating
                its traces.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.THREAD_ENDPOINT,
            response_schema=Thread,
            path={"threadId": thread_id},
        )

    async def a_get(self, thread_id: str) -> Thread:
        """Get Thread

        Retrieves a thread by id from your Confident AI project, with its
        evaluation results, annotations and the first 100 traces of the
        conversation, oldest first.

        Args:
            thread_id: The id of the thread, as you supplied it when creating
                its traces.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.THREAD_ENDPOINT,
            response_schema=Thread,
            path={"threadId": thread_id},
        )
