// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: forwarding-connectors).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import {
  ForwardingConnector,
  ForwardingConnectorHeaderConfig,
  ForwardingConnectorList,
  ForwardingConnectorRef,
} from "./types";

export class ForwardingConnectorsClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Forwarding Connectors
   *
   * Lists the forwarding connectors in your Confident AI project one page at a
   * time, newest first. Each connector is returned as a summary; retrieve one
   * by id for its headers, environments and delivery history.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async list(
    page?: number,
    pageSize?: number,
  ): Promise<ForwardingConnectorList> {
    return this.api.sendRequest<ForwardingConnectorList>(
      HttpMethods.GET,
      Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
      { params: { page, pageSize } },
    );
  }

  /**
   * Create Forwarding Connector
   *
   * Creates a forwarding connector in your Confident AI project and returns its
   * id. Confident AI then forwards traces from the environments you selected to
   * your OTLP/HTTP collector, sending the headers you supplied with every
   * batch. Header values are stored write-only: they are masked on every read,
   * so keep your own copy.
   *
   * @param name The name of the connector, shown on the Confident AI platform
   *   and in forwarding failure messages.
   * @param endpoint The HTTPS URL of the OTLP/HTTP collector that receives the
   *   forwarded traces. It must resolve to a public address; private and
   *   loopback addresses are rejected.
   * @param headers The complete set of HTTP headers to send with every
   *   forwarded batch, alongside the `Content-Type: application/x-protobuf`
   *   header Confident AI sets. Omit this field to leave the stored headers
   *   untouched. When you do send it, the list replaces all stored headers, so
   *   resend every header you want to keep — including the ones whose values
   *   you read back masked, which are kept as stored.
   * @param environments The environments whose traces this connector forwards.
   *   An empty list forwards traces from every environment. Omit this field to
   *   leave the stored environments unchanged.
   * @param enabled Whether the connector forwards traces. Defaults to `true` on
   *   create; omit it on an update to leave it unchanged.
   */
  async create(
    name: string,
    endpoint: string,
    options: {
      headers?: ForwardingConnectorHeaderConfig[];
      environments?: string[];
      enabled?: boolean;
    } = {},
  ): Promise<ForwardingConnectorRef> {
    const { headers, environments, enabled } = options;
    return this.api.sendRequest<ForwardingConnectorRef>(
      HttpMethods.POST,
      Endpoints.FORWARDING_CONNECTORS_ENDPOINT,
      { body: { name, endpoint, headers, environments, enabled } },
    );
  }

  /**
   * Get Forwarding Connector
   *
   * Retrieves a forwarding connector by id, with its headers, the environments
   * it forwards, and how its deliveries have gone. Header values come back
   * masked, never in plaintext.
   *
   * @param forwardingConnectorId The id of the forwarding connector.
   */
  async get(forwardingConnectorId: string): Promise<ForwardingConnector> {
    return this.api.sendRequest<ForwardingConnector>(
      HttpMethods.GET,
      Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
      { urlParams: { forwardingConnectorId } },
    );
  }

  /**
   * Update Forwarding Connector
   *
   * Updates a forwarding connector and returns it. Every field you omit is left
   * as stored.
   *
   * @param forwardingConnectorId The id of the forwarding connector.
   * @param name The name of the connector.
   * @param endpoint The HTTPS URL of the OTLP/HTTP collector that receives the
   *   forwarded traces. It must resolve to a public address; private and
   *   loopback addresses are rejected.
   * @param headers The complete set of HTTP headers to send with every
   *   forwarded batch, alongside the `Content-Type: application/x-protobuf`
   *   header Confident AI sets. Omit this field to leave the stored headers
   *   untouched. When you do send it, the list replaces all stored headers, so
   *   resend every header you want to keep — including the ones whose values
   *   you read back masked, which are kept as stored.
   * @param environments The environments whose traces this connector forwards.
   *   An empty list forwards traces from every environment. Omit this field to
   *   leave the stored environments unchanged.
   * @param enabled Whether the connector forwards traces. Defaults to `true` on
   *   create; omit it on an update to leave it unchanged.
   */
  async update(
    forwardingConnectorId: string,
    options: {
      name?: string;
      endpoint?: string;
      headers?: ForwardingConnectorHeaderConfig[];
      environments?: string[];
      enabled?: boolean;
    } = {},
  ): Promise<ForwardingConnector> {
    const { name, endpoint, headers, environments, enabled } = options;
    return this.api.sendRequest<ForwardingConnector>(
      HttpMethods.PUT,
      Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
      {
        body: { name, endpoint, headers, environments, enabled },
        urlParams: { forwardingConnectorId },
      },
    );
  }

  /**
   * Delete Forwarding Connector
   *
   * Permanently deletes a forwarding connector and the credentials stored in
   * its headers. Traces already forwarded are unaffected.
   *
   * @param forwardingConnectorId The id of the forwarding connector.
   */
  async delete(forwardingConnectorId: string): Promise<ForwardingConnectorRef> {
    return this.api.sendRequest<ForwardingConnectorRef>(
      HttpMethods.DELETE,
      Endpoints.FORWARDING_CONNECTOR_ENDPOINT,
      { urlParams: { forwardingConnectorId } },
    );
  }
}
