// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: forwarding-connectors).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

export interface ForwardingConnectorHeaderConfig {
  key: string;
  value: string;
}

export interface CreateForwardingConnectorRequest {
  name: string;
  endpoint: string;
  headers?: ForwardingConnectorHeaderConfig[];
  environments?: string[];
  enabled?: boolean;
}

export interface ForwardingConnectorHeader {
  key: string;
  value: string;
}

export interface ForwardingConnector {
  id: string;
  name: string;
  endpoint: string;
  headers: ForwardingConnectorHeader[];
  environments: string[];
  enabled: boolean;
  lastForwardedAt: string | null;
  lastError: string | null;
  successCount: number;
  failureCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface ForwardingConnectorSummary {
  id: string;
  name: string;
  endpoint: string;
  enabled: boolean;
}

export interface ForwardingConnectorList {
  forwardingConnectors: ForwardingConnectorSummary[];
  totalForwardingConnectors: number;
  page: number;
  pageSize: number;
}

export interface ForwardingConnectorRef {
  id: string;
}

export interface UpdateForwardingConnectorRequest {
  name?: string;
  endpoint?: string;
  headers?: ForwardingConnectorHeaderConfig[];
  environments?: string[];
  enabled?: boolean;
}
