# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: export-schedules).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Literal, Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.common.types import (
    FilterSet,
    ScheduleIntervalUnit,
    ScheduleRecurrenceType,
)
from confident_ai.endpoints import Endpoints
from confident_ai.export_schedules.types import (
    AnnotationSelectionType,
    CreateExportScheduleRequest,
    ExportSchedule,
    ExportScheduleList,
    ExportScheduleRef,
    SchedulableExportType,
    UpdateExportScheduleRequest,
)


class ExportSchedulesClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        export_type: Optional[SchedulableExportType] = None,
        enabled: Optional[Literal["true", "false"]] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> ExportScheduleList:
        """List Export Schedules

        Lists the export schedules in your Confident AI project one page at a
        time, newest first. Narrow the page with `exportType` or `enabled`;
        retrieve one by id to see its cadence, filters and destination.

        Args:
            enabled: Return only the schedules that are currently running, or
                only those that are paused. Omit it for both.
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.EXPORT_SCHEDULES_ENDPOINT,
            response_schema=ExportScheduleList,
            query={
                "exportType": export_type,
                "enabled": enabled,
                "page": page,
                "pageSize": page_size,
            },
        )

    async def a_list(
        self,
        *,
        export_type: Optional[SchedulableExportType] = None,
        enabled: Optional[Literal["true", "false"]] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> ExportScheduleList:
        """List Export Schedules

        Lists the export schedules in your Confident AI project one page at a
        time, newest first. Narrow the page with `exportType` or `enabled`;
        retrieve one by id to see its cadence, filters and destination.

        Args:
            enabled: Return only the schedules that are currently running, or
                only those that are paused. Omit it for both.
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.EXPORT_SCHEDULES_ENDPOINT,
            response_schema=ExportScheduleList,
            query={
                "exportType": export_type,
                "enabled": enabled,
                "page": page,
                "pageSize": page_size,
            },
        )

    def create(
        self,
        name: str,
        export_type: SchedulableExportType,
        *,
        recurrence: Optional[ScheduleRecurrenceType] = None,
        repeat_every: Optional[int] = None,
        repeat_unit: Optional[ScheduleIntervalUnit] = None,
        start_at: Optional[str] = None,
        max_runs: Optional[int] = None,
        end_at: Optional[str] = None,
        description: Optional[str] = None,
        filters: Optional[FilterSet] = None,
        environment: Optional[str] = None,
        annotation_selection_type: Optional[AnnotationSelectionType] = None,
        destination_id: Optional[str] = None,
        enabled: Optional[bool] = None
    ) -> ExportScheduleRef:
        """Create Export Schedule

        Creates an export schedule in your Confident AI project and returns its
        id. Each run exports the window since the previous run and delivers it
        to the export destination you name, so a schedule starts producing files
        as soon as it is enabled.

        Args:
            name: The name of the schedule.
            repeat_every: How many `repeatUnit`s apart the runs are, for an
                `INTERVAL` schedule. Send `null` to clear it.
            repeat_unit: The unit `repeatEvery` counts, for an `INTERVAL`
                schedule. Send `null` to clear it.
            start_at: When the schedule first runs, as an ISO 8601 datetime.
                Send `null` to start it immediately.
            max_runs: How many times the schedule runs before it stops. Send
                `null` to let it run indefinitely.
            end_at: When the schedule stops running, as an ISO 8601 datetime.
                Send `null` to leave it open-ended.
            description: What the schedule exports. Send `null` to leave it
                unset.
            environment: The environment each run exports data from. Omit it, or
                send `null`, to export data from every environment. Ignored for
                `TEST_RUNS` exports, which have no environment.
            annotation_selection_type: The annotation source for each
                `ANNOTATIONS` export run. Omit it, or send `null`, to export
                annotations from every source. Ignored for other export types.
            destination_id: The id of the export destination each run delivers
                its file to. A scheduled run has no recipient of its own, so a
                schedule created without a destination produces files that go
                nowhere.
            enabled: Whether the schedule starts running as soon as it is
                created. Defaults to `true`.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.EXPORT_SCHEDULES_ENDPOINT,
            response_schema=ExportScheduleRef,
            request_schema=CreateExportScheduleRequest,
            body={
                "name": name,
                "exportType": export_type,
                "recurrence": recurrence,
                "repeatEvery": repeat_every,
                "repeatUnit": repeat_unit,
                "startAt": start_at,
                "maxRuns": max_runs,
                "endAt": end_at,
                "description": description,
                "filters": filters,
                "environment": environment,
                "annotationSelectionType": annotation_selection_type,
                "destinationId": destination_id,
                "enabled": enabled,
            },
        )

    async def a_create(
        self,
        name: str,
        export_type: SchedulableExportType,
        *,
        recurrence: Optional[ScheduleRecurrenceType] = None,
        repeat_every: Optional[int] = None,
        repeat_unit: Optional[ScheduleIntervalUnit] = None,
        start_at: Optional[str] = None,
        max_runs: Optional[int] = None,
        end_at: Optional[str] = None,
        description: Optional[str] = None,
        filters: Optional[FilterSet] = None,
        environment: Optional[str] = None,
        annotation_selection_type: Optional[AnnotationSelectionType] = None,
        destination_id: Optional[str] = None,
        enabled: Optional[bool] = None
    ) -> ExportScheduleRef:
        """Create Export Schedule

        Creates an export schedule in your Confident AI project and returns its
        id. Each run exports the window since the previous run and delivers it
        to the export destination you name, so a schedule starts producing files
        as soon as it is enabled.

        Args:
            name: The name of the schedule.
            repeat_every: How many `repeatUnit`s apart the runs are, for an
                `INTERVAL` schedule. Send `null` to clear it.
            repeat_unit: The unit `repeatEvery` counts, for an `INTERVAL`
                schedule. Send `null` to clear it.
            start_at: When the schedule first runs, as an ISO 8601 datetime.
                Send `null` to start it immediately.
            max_runs: How many times the schedule runs before it stops. Send
                `null` to let it run indefinitely.
            end_at: When the schedule stops running, as an ISO 8601 datetime.
                Send `null` to leave it open-ended.
            description: What the schedule exports. Send `null` to leave it
                unset.
            environment: The environment each run exports data from. Omit it, or
                send `null`, to export data from every environment. Ignored for
                `TEST_RUNS` exports, which have no environment.
            annotation_selection_type: The annotation source for each
                `ANNOTATIONS` export run. Omit it, or send `null`, to export
                annotations from every source. Ignored for other export types.
            destination_id: The id of the export destination each run delivers
                its file to. A scheduled run has no recipient of its own, so a
                schedule created without a destination produces files that go
                nowhere.
            enabled: Whether the schedule starts running as soon as it is
                created. Defaults to `true`.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.EXPORT_SCHEDULES_ENDPOINT,
            response_schema=ExportScheduleRef,
            request_schema=CreateExportScheduleRequest,
            body={
                "name": name,
                "exportType": export_type,
                "recurrence": recurrence,
                "repeatEvery": repeat_every,
                "repeatUnit": repeat_unit,
                "startAt": start_at,
                "maxRuns": max_runs,
                "endAt": end_at,
                "description": description,
                "filters": filters,
                "environment": environment,
                "annotationSelectionType": annotation_selection_type,
                "destinationId": destination_id,
                "enabled": enabled,
            },
        )

    def get(self, export_schedule_id: str) -> ExportSchedule:
        """Get Export Schedule

        Retrieves an export schedule by id, with the filters and destination
        each of its runs uses.

        Args:
            export_schedule_id: The id of the export schedule.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportSchedule,
            path={"exportScheduleId": export_schedule_id},
        )

    async def a_get(self, export_schedule_id: str) -> ExportSchedule:
        """Get Export Schedule

        Retrieves an export schedule by id, with the filters and destination
        each of its runs uses.

        Args:
            export_schedule_id: The id of the export schedule.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportSchedule,
            path={"exportScheduleId": export_schedule_id},
        )

    def update(
        self,
        export_schedule_id: str,
        *,
        recurrence: Optional[ScheduleRecurrenceType] = None,
        repeat_every: Optional[int] = None,
        repeat_unit: Optional[ScheduleIntervalUnit] = None,
        start_at: Optional[str] = None,
        max_runs: Optional[int] = None,
        end_at: Optional[str] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        filters: Optional[FilterSet] = None,
        environment: Optional[str] = None,
        annotation_selection_type: Optional[AnnotationSelectionType] = None,
        destination_id: Optional[str] = None,
        enabled: Optional[bool] = None
    ) -> ExportSchedule:
        """Update Export Schedule

        Changes an export schedule and returns it. Changing the cadence or
        pausing the schedule re-registers its next run; `exportType` is fixed at
        creation, because changing it would re-target every future run.

        Args:
            export_schedule_id: The id of the export schedule.
            repeat_every: How many `repeatUnit`s apart the runs are, for an
                `INTERVAL` schedule. Send `null` to clear it.
            repeat_unit: The unit `repeatEvery` counts, for an `INTERVAL`
                schedule. Send `null` to clear it.
            start_at: When the schedule first runs, as an ISO 8601 datetime.
                Send `null` to start it immediately.
            max_runs: How many times the schedule runs before it stops. Send
                `null` to let it run indefinitely.
            end_at: When the schedule stops running, as an ISO 8601 datetime.
                Send `null` to leave it open-ended.
            name: The name of the schedule.
            description: What the schedule exports. Send `null` to clear it.
            environment: The environment each run exports data from. Send `null`
                to export data from every environment. Ignored for `TEST_RUNS`
                exports, which have no environment.
            annotation_selection_type: The annotation source for each
                `ANNOTATIONS` export run. Send `null` to export annotations from
                every source. Ignored for other export types.
            destination_id: The id of the export destination each run delivers
                its file to. Send `null` to leave the schedule without one.
            enabled: Whether the schedule runs. Send `false` to pause it without
                deleting it.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportSchedule,
            request_schema=UpdateExportScheduleRequest,
            body={
                "recurrence": recurrence,
                "repeatEvery": repeat_every,
                "repeatUnit": repeat_unit,
                "startAt": start_at,
                "maxRuns": max_runs,
                "endAt": end_at,
                "name": name,
                "description": description,
                "filters": filters,
                "environment": environment,
                "annotationSelectionType": annotation_selection_type,
                "destinationId": destination_id,
                "enabled": enabled,
            },
            path={"exportScheduleId": export_schedule_id},
        )

    async def a_update(
        self,
        export_schedule_id: str,
        *,
        recurrence: Optional[ScheduleRecurrenceType] = None,
        repeat_every: Optional[int] = None,
        repeat_unit: Optional[ScheduleIntervalUnit] = None,
        start_at: Optional[str] = None,
        max_runs: Optional[int] = None,
        end_at: Optional[str] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        filters: Optional[FilterSet] = None,
        environment: Optional[str] = None,
        annotation_selection_type: Optional[AnnotationSelectionType] = None,
        destination_id: Optional[str] = None,
        enabled: Optional[bool] = None
    ) -> ExportSchedule:
        """Update Export Schedule

        Changes an export schedule and returns it. Changing the cadence or
        pausing the schedule re-registers its next run; `exportType` is fixed at
        creation, because changing it would re-target every future run.

        Args:
            export_schedule_id: The id of the export schedule.
            repeat_every: How many `repeatUnit`s apart the runs are, for an
                `INTERVAL` schedule. Send `null` to clear it.
            repeat_unit: The unit `repeatEvery` counts, for an `INTERVAL`
                schedule. Send `null` to clear it.
            start_at: When the schedule first runs, as an ISO 8601 datetime.
                Send `null` to start it immediately.
            max_runs: How many times the schedule runs before it stops. Send
                `null` to let it run indefinitely.
            end_at: When the schedule stops running, as an ISO 8601 datetime.
                Send `null` to leave it open-ended.
            name: The name of the schedule.
            description: What the schedule exports. Send `null` to clear it.
            environment: The environment each run exports data from. Send `null`
                to export data from every environment. Ignored for `TEST_RUNS`
                exports, which have no environment.
            annotation_selection_type: The annotation source for each
                `ANNOTATIONS` export run. Send `null` to export annotations from
                every source. Ignored for other export types.
            destination_id: The id of the export destination each run delivers
                its file to. Send `null` to leave the schedule without one.
            enabled: Whether the schedule runs. Send `false` to pause it without
                deleting it.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportSchedule,
            request_schema=UpdateExportScheduleRequest,
            body={
                "recurrence": recurrence,
                "repeatEvery": repeat_every,
                "repeatUnit": repeat_unit,
                "startAt": start_at,
                "maxRuns": max_runs,
                "endAt": end_at,
                "name": name,
                "description": description,
                "filters": filters,
                "environment": environment,
                "annotationSelectionType": annotation_selection_type,
                "destinationId": destination_id,
                "enabled": enabled,
            },
            path={"exportScheduleId": export_schedule_id},
        )

    def delete(self, export_schedule_id: str) -> ExportScheduleRef:
        """Delete Export Schedule

        Permanently deletes an export schedule and unregisters its next run.
        Files its earlier runs already delivered are kept.

        Args:
            export_schedule_id: The id of the export schedule.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportScheduleRef,
            path={"exportScheduleId": export_schedule_id},
        )

    async def a_delete(self, export_schedule_id: str) -> ExportScheduleRef:
        """Delete Export Schedule

        Permanently deletes an export schedule and unregisters its next run.
        Files its earlier runs already delivered are kept.

        Args:
            export_schedule_id: The id of the export schedule.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.EXPORT_SCHEDULE_ENDPOINT,
            response_schema=ExportScheduleRef,
            path={"exportScheduleId": export_schedule_id},
        )
