# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: export-schedules).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import List, Optional

from pydantic import Field

from confident_ai.common.types import (
    FilterSet,
    ScheduleIntervalUnit,
    ScheduleRecurrenceType,
)
from confident_ai.types import ConfidentBaseModel


class AnnotationSelectionType(Enum):
    SPANS = "Spans"
    THREADS = "Threads"
    TRACES = "Traces"


class SchedulableExportType(Enum):
    TRACES = "TRACES"
    TRACES_WITH_SPANS = "TRACES_WITH_SPANS"
    CONVERSATIONS = "CONVERSATIONS"
    CONVERSATION_METRICS = "CONVERSATION_METRICS"
    ANNOTATIONS = "ANNOTATIONS"
    TEST_RUNS = "TEST_RUNS"
    AUDIT_LOGS = "AUDIT_LOGS"


class CreateExportScheduleRequest(ConfidentBaseModel):
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")
    name: str
    description: Optional[str] = None
    export_type: SchedulableExportType = Field(alias="exportType")
    filters: Optional[FilterSet] = None
    environment: Optional[str] = None
    annotation_selection_type: Optional[AnnotationSelectionType] = Field(
        default=None,
        alias="annotationSelectionType",
    )
    destination_id: Optional[str] = Field(default=None, alias="destinationId")
    enabled: Optional[bool] = None


class ExportScheduleSettings(ConfidentBaseModel):
    recurrence: ScheduleRecurrenceType
    repeat_every: Optional[int] = Field(alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(alias="repeatUnit")
    start_at: Optional[str] = Field(alias="startAt")
    end_at: Optional[str] = Field(alias="endAt")
    max_runs: Optional[int] = Field(alias="maxRuns")
    run_count: int = Field(alias="runCount")
    last_run_at: Optional[str] = Field(alias="lastRunAt")
    enabled: bool


class ExportSchedule(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]
    export_type: SchedulableExportType = Field(alias="exportType")
    filters: FilterSet
    environment: Optional[str]
    annotation_selection_type: Optional[AnnotationSelectionType] = Field(
        alias="annotationSelectionType",
    )
    destination_id: Optional[str] = Field(alias="destinationId")
    schedule_settings: Optional[ExportScheduleSettings] = Field(
        alias="scheduleSettings",
    )
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")


class ExportScheduleSummary(ConfidentBaseModel):
    id: str
    name: str
    export_type: SchedulableExportType = Field(alias="exportType")
    enabled: bool


class ExportScheduleList(ConfidentBaseModel):
    export_schedules: List[ExportScheduleSummary] = Field(
        alias="exportSchedules",
    )
    total_export_schedules: int = Field(alias="totalExportSchedules")
    page: int
    page_size: int = Field(alias="pageSize")


class ExportScheduleRef(ConfidentBaseModel):
    id: str


class UpdateExportScheduleRequest(ConfidentBaseModel):
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")
    name: Optional[str] = None
    description: Optional[str] = None
    filters: Optional[FilterSet] = None
    environment: Optional[str] = None
    annotation_selection_type: Optional[AnnotationSelectionType] = Field(
        default=None,
        alias="annotationSelectionType",
    )
    destination_id: Optional[str] = Field(default=None, alias="destinationId")
    enabled: Optional[bool] = None
